import { useRouter } from "next/router";
import {
  useEffect,
  //useRef
} from "react";
import Head from "next/head";
import Image from "next/image";
import { Carousel } from "react-bootstrap";
import { TbGridDots } from "react-icons/tb";
import { IoMdNotificationsOutline } from "react-icons/io";
import { IoIosArrowDown } from "react-icons/io";
import { HiOutlineDotsHorizontal } from "react-icons/hi";
import { IoMdSearch } from "react-icons/io";
import { Geist, Geist_Mono } from "next/font/google";
import { IoIosArrowBack, IoIosArrowForward } from "react-icons/io";
import { FaRegEye } from "react-icons/fa";
import { FaUserPlus } from "react-icons/fa6";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function PrevArrow(props: any) {
  const { onClick } = props;
  return (
    <span className="slider-arrow left" onClick={onClick}>
      <IoIosArrowBack />
    </span>
  );
}

function NextArrow(props: any) {
  const { onClick } = props;
  return (
    <span className="slider-arrow right" onClick={onClick}>
      <IoIosArrowForward />
    </span>
  );
}

export default function FeedPage() {
  const router = useRouter();
  useEffect(() => {
    document.body.classList.add("feed-body");
    return () => {
      document.body.classList.remove("feed-body");
    };
  }, []);
  /* 🔹 FEED DATA (Dynamic) */
  const feedData = [
    {
      id: 1,
      user: "Railly Watson",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
      text: "Golden, comforting, and irresistibly flavorful—this dish is a celebration of taste and tradition.",
      images: [
        "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
        "/images/bgga.png",
      ],
    },
    {
      id: 2,
      user: "James Garry",
      avatar: "https://randomuser.me/api/portraits/men/33.jpg",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non diam eleifend.",
      images: [],
    },
    {
      id: 3,
      user: "Sam Stain",
      avatar: "https://randomuser.me/api/portraits/men/31.jpg",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc malesuada magna orci.",
      images: ["https://images.unsplash.com/photo-1501785888041-af3ef285b470"],
    },
    {
      id: 4,
      user: "Luna Rodrigage",
      avatar: "https://randomuser.me/api/portraits/women/43.jpg",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non diam eleifend.",
      images: [],
    },
    {
      id: 5,
      user: "Shinomi Watts",
      avatar: "https://randomuser.me/api/portraits/women/60.jpg",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non diam eleifend.",
      images: ["/images/bga.png"],
    },
    {
      id: 6,
      user: "Korey Jackson",
      avatar: "https://randomuser.me/api/portraits/women/10.jpg",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non diam eleifend.",
      images: [],
    },
  ];
  return (
    <>
      <Head>
        <title>TensorCrest – Feed Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
      </Head>
      <header className="fnav">
        <div className="logo">
          <Image
            src="/logo.svg"
            alt="ResearchCrest Logo"
            width={160}
            height={40}
            priority
          />
        </div>
        <div className="search">
          <input type="text" placeholder="Search In Tensor Crest" />
        </div>
        <nav className="feed-menu">
          <a>Home</a>
          <a>Q&amp;A</a>
          <a>Network</a>
          <a>career</a>
          <a>Scholarship</a>
          <a href="#" className="nine-dots">
            <TbGridDots
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.2rem",
                color: "#000",
              }}
            />
          </a>
          <a>
            <IoMdNotificationsOutline
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.3rem",
                color: "#000",
              }}
            />
          </a>
          <a className="profile-wrapper">
            <img src="/images/prof.jpg" alt="" className="menu-logo" />
            <IoIosArrowDown className="arrow-icon" />
          </a>
        </nav>
      </header>
      <div className="feed-page">
        <div className="left-content">
          <aside className="profile-card">
            <div
              className="profile-header"
              style={{
                backgroundImage: "url('/images/cvr.jpg')",
              }}
            >
              <img src="/images/prof.jpg" alt="" />
            </div>
            <div className="profile-body pad">
              {/* <h4
                onClick={() => router.push("/profile-page")}
                style={{ cursor: "pointer" }}
              >
                Brand Gardner
              </h4> */}
              <div className="namee-row cntr">
                <h4
                  className="name hd"
                  onClick={() => router.push("/profile-page")}
                  style={{ cursor: "pointer" }}
                >
                  Brand Gardner
                </h4>
                <img
                  src="/images/icons/vrfd.svg"
                  alt="verified-tag"
                  className="vrfd-tg"
                />
              </div>
              <p className="subttl">
                Assistant General Manager - HR | Business HR & Strategy
                <br />
                MHRM (University of London)
              </p>

              <div className="profile-stats">
                <div>
                  <span>
                    <h3>Publications</h3>
                  </span>
                  <span>42</span>
                </div>
                <div>
                  <span>
                    <h3>h-index</h3>
                  </span>
                  <span>18</span>
                </div>
                <div>
                  <span>
                    <h3>Followers</h3>
                  </span>
                  <span>324</span>
                </div>
              </div>

              <div className="profile-tags">
                <span>CSE</span>
                <span>Current Affiliations: 50</span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </div>
              <div className="profile-section">
                <h3>Domain & Classification:</h3>
                <p>
                  Electrical Engineering
                  <br />
                  Faculty of Technology
                  <br />
                  Advance Polymers and Composite Research Group
                </p>
              </div>
              <div className="profile-section">
                <h3>Research Interests:</h3>
                <p>
                  Renewable Energy,
                  <br />
                  Internet of Things,
                  <br />
                  Machine Learning
                </p>
              </div>
              <div className="profile-section">
                <h3>Education:</h3>
                <p>
                  University of California - Los Angeles (MS. in CS)
                  <br />
                  Massachusetts Institute of Technology (BSc. in CSE)
                  <br />
                </p>
              </div>
              <div className="profile-section">
                <h3>BSc. Advisors:</h3>
                <p className="green">
                  Dr. Emily Carter
                  <br />
                  Dr. Steven Harris
                </p>
              </div>
              <div className="profile-section">
                <h3>MS Advisors:</h3>
                <p className="green">
                  Prof. Dr. Jonathan Miles
                  <br />
                  Prof. Dr. Rebecca Thornton
                </p>
              </div>
              <div className="profile-section">
                <h3>Awards:</h3>
                <p className="green">Dijkstra Prize</p>
              </div>
            </div>
          </aside>
        </div>
        <div className="feed-content">
          {/* HEADER */}
          <div className="feed-header">
            <div>
              {/* <input type="text" placeholder="Search" /> */}
              <IoMdSearch className="sch-icon srchbr-icn" />
              <div className="feed-actions">
                <span>
                  <Image
                    src="/images/icons/srch.svg"
                    alt="Search Icon"
                    width={45}
                    height={45}
                    priority
                    className="srchbr-icn"
                  />
                </span>
              </div>
            </div>
            <div>
              <span className="icn">
                <Image
                  src="/images/icons/ply.svg"
                  alt=""
                  width={45}
                  height={45}
                  className="srchbr-icn"
                />
              </span>
              <span className="icn">
                <Image
                  src="/images/icons/phto.svg"
                  alt=""
                  width={45}
                  height={45}
                  className="srchbr-icn"
                />
              </span>
              <span className="icn">
                <Image
                  src="/images/icons/ppr.svg"
                  alt=""
                  width={45}
                  height={45}
                  className="srchbr-icn"
                />
              </span>
            </div>
          </div>
          {/* 🔹 DYNAMIC FEED CARDS */}
          {feedData.map((item) => (
            <div className="feed-card" key={item.id}>
              <div className="feed-top">
                <div className="feed-user">
                  <img src={item.avatar} alt={item.user} />
                  <span>{item.user}</span>
                </div>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </div>

              <p className="feed-text">{item.text}</p>

              {/* IMAGES (Conditional) */}
              {item.images.length > 0 && (
                <div className="feed-immg">
                  {item.images.map((img, i) => (
                    <img key={i} src={img} className="feed-img sm" />
                  ))}
                </div>
              )}

              {/* ACTIONS */}
              <div className="feed-actions-row">
                <div className="left-icn">
                  <span>
                    <Image
                      src="/images/icons/hrt.svg"
                      alt=""
                      width={15}
                      height={15}
                    />
                  </span>
                  <span>
                    <Image
                      src="/images/icons/cht.svg"
                      alt=""
                      width={15}
                      height={15}
                    />
                  </span>
                  <span>
                    <Image
                      src="/images/icons/shr.svg"
                      alt=""
                      width={15}
                      height={15}
                    />
                  </span>
                </div>
                <span>
                  <Image
                    src="/images/icons/wslst.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
            </div>
          ))}
        </div>
        <div className="right-content">
          <div className="side-card artl-card">
            <h4 className="side-title">SUGGESTED ARTICLE / BLOG</h4>
            <div className="article-item sm">
              <img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b" />
              <div>
                <span className="tag orange">EDUCATION</span>
                <p>
                  In an era of budget cuts, funding for science and research is
                  being slashed
                </p>
                <small>August 22 · 8:48 pm</small>
              </div>
            </div>
            <div className="article-item sm">
              <img src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d" />
              <div>
                <span className="tag green">SOCIETY</span>
                <p>
                  The Safety Council has issued the following news release
                  regarding…
                </p>
                <small>August 22 · 8:40 pm</small>
              </div>
            </div>

            <button className="read-more crv">READ MORE</button>
          </div>
          {/* <!-- POST ACTIVITY --> */}
          <div className="side-card activity-card">
            <div className="side-headerpst">
              <h4>POST ACTIVITY</h4>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/women/12.jpg" />
              <span>My Wedding Celebration</span>
              <div className="right-ico">
                <span>
                  <FaRegEye />
                </span>
                <b>7,890</b>
              </div>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/men/44.jpg" />
              <span>Christmas Celebration</span>
              <div className="right-ico">
                <span>
                  <FaRegEye />
                </span>
                <b>600</b>
              </div>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/women/32.jpg" />
              <span>My Graduation</span>
              <div className="right-ico">
                <span>
                  <FaRegEye />
                </span>
                <b>390</b>
              </div>
            </div>
            <button className="read-more crv">SEE MORE</button>
          </div>
          {/* <!-- NOTABLE --> */}
          <div className="side-card notable-card">
            <div className="side-headerpst">
              <h4>NOTABLE</h4>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>
            <Carousel
              indicators={false}
              controls={true}
              interval={null}
              className="notable-carousel"
            >
              <Carousel.Item>
                <div className="notable-row">
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/men/45.jpg" />
                    <p>Alfredo</p>
                    <span>Professor</span>
                    <p className="sub">alfredo@gmail.com</p>
                  </div>
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/women/52.jpg" />
                    <p>Cahaya</p>
                    <span>Teacher</span>
                    <p>cahaya@gmail.com</p>
                  </div>
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/women/68.jpg" />
                    <p>Mariana</p>
                    <span>Student</span>
                    <p>mariana@gmail.com</p>
                  </div>
                </div>
              </Carousel.Item>
              <Carousel.Item>
                <div className="notable-row">
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/men/46.jpg" />
                    <p>James</p>
                    <span>Professor</span>
                    <p className="sub">alfredo@gmail.com</p>
                  </div>
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/women/53.jpg" />
                    <p>Susan</p>
                    <span>Teacher</span>
                    <p>susan@gmail.com</p>
                  </div>
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/women/69.jpg" />
                    <p>Linda</p>
                    <span>Student</span>
                    <p>linda@gmail.com</p>
                  </div>
                </div>
              </Carousel.Item>
            </Carousel>
            <button className="read-more crv">SEE MORE</button>
          </div>
          <section className="side-card suggst-section">
            <h4 className="resrch-titl-left sm">YOU MAY LIKE</h4>
            <p className="subb">Pages for you</p>
            <div className="suggest-list">
              <div className="suggest-item">
                <div className="suggest-left">
                  <img
                    src="/images/scigrp.jpg"
                    className="suggest-avatar-img"
                  />
                  <span>Science Group</span>
                </div>
                <button className="follow-btn">
                  <FaUserPlus /> Follow
                </button>
              </div>
              <div className="suggest-item">
                <div className="suggest-left">
                  <img
                    src="https://randomuser.me/api/portraits/men/40.jpg"
                    className="suggest-avatar-img"
                  />
                  <span>Research Group</span>
                </div>
                <button className="follow-btn">
                  <FaUserPlus /> Follow
                </button>
              </div>
            </div>
          </section>
        </div>
      </div>
      {/* <footer className="site-footer">
        <div className="footer-top">
          <div className="footer-left">
            <h3 className="footer-logo">ResearchCrest</h3>
            <p>
              Stay in the know by subscribing to our
              <br />
              newsletter below
            </p>

            <div className="newsletter">
              <input type="email" placeholder="Enter your email address" />
              <button>→</button>
            </div>
          </div>

          <div className="footer-right">
            <div className="footer-col">
              <h4>Contact</h4>
              <a href="#">Contact Form</a>
              <a href="#">FAQ</a>
              <a href="#">Privacy Policy</a>
              <a href="#">T&amp;C</a>
            </div>

            <div className="footer-col">
              <h4>Social</h4>
              <a href="#">Facebook</a>
              <a href="#">Youtube</a>
              <a href="#">Twitter</a>
              <a href="#">LinkedIn</a>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <span>© Researchcrest. All Rights Reserved 2023</span>
          <span>Terms &amp; Conditions</span>
        </div>
      </footer> */}
    </>
  );
}
