import { useRouter } from "next/router";
import {
  useState,
  useEffect,
  useRef,
  useCallback
} from "react";
import Head from "next/head";
import Image from "next/image";
import { Carousel } from "react-bootstrap";
import { TbGridDots } from "react-icons/tb";
import { IoMdNotificationsOutline } from "react-icons/io";
import { IoIosArrowDown } from "react-icons/io";
import { HiOutlineDotsHorizontal } from "react-icons/hi";
import { IoMdSearch } from "react-icons/io";
import { Geist, Geist_Mono } from "next/font/google";
import { useFeed } from "@/hooks/useFeed";
import moment from "moment";
import { IoIosArrowBack, IoIosArrowForward } from "react-icons/io";
import { FaRegEye } from "react-icons/fa";
import { FaUserPlus } from "react-icons/fa6";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function PrevArrow(props: any) {
  const { onClick } = props;
  return (
    <span className="slider-arrow left" onClick={onClick}>
      <IoIosArrowBack />
    </span>
  );
}

function NextArrow(props: any) {
  const { onClick } = props;
  return (
    <span className="slider-arrow right" onClick={onClick}>
      <IoIosArrowForward />
    </span>
  );
}

export default function FeedPage() {
  const router = useRouter();
  const {
    feedData,
    posts,
    isLoading,
    isFetchingMore,
    hasMore,
    error,
    loadMore,
    createPost,
    toggleLike
  } = useFeed(10);

  const [postText, setPostText] = useState("");
  const [isPosting, setIsPosting] = useState(false);

  useEffect(() => {
    document.body.classList.add("feed-body");
    return () => {
      document.body.classList.remove("feed-body");
    };
  }, []);

  const observer = useRef<IntersectionObserver | null>(null);
  const lastPostElementRef = useCallback(
    (node: HTMLDivElement) => {
      if (isFetchingMore) return;
      if (observer.current) observer.current.disconnect();

      observer.current = new IntersectionObserver((entries) => {
        if (entries[0].isIntersecting && hasMore) {
          loadMore();
        }
      });

      if (node) observer.current.observe(node);
    },
    [isFetchingMore, hasMore, loadMore]
  );

  const handleCreatePost = async () => {
    if (!postText.trim()) return;
    setIsPosting(true);
    const success = await createPost({ post_text: postText, visibility: "public" });
    if (success) {
      setPostText("");
    }
    setIsPosting(false);
  };
  return (
    <>
      <Head>
        <title>TensorCrest – Feed Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
      </Head>
      <header className="fnav">
        <div className="logo">
          <Image
            src="/logo.svg"
            alt="ResearchCrest Logo"
            width={160}
            height={40}
            priority
          />
        </div>
        <div className="search">
          <input type="text" placeholder="Search In Tensor Crest" />
        </div>
        <nav className="feed-menu">
          <a>Home</a>
          <a>Q&amp;A</a>
          <a>Network</a>
          <a>career</a>
          <a>Scholarship</a>
          <a href="#" className="nine-dots">
            <TbGridDots
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.2rem",
                color: "#000",
              }}
            />
          </a>
          <a>
            <IoMdNotificationsOutline
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.3rem",
                color: "#000",
              }}
            />
          </a>
          <a className="profile-wrapper">
            <img src="/images/prof.jpg" alt="" className="menu-logo" />
            <IoIosArrowDown className="arrow-icon" />
          </a>
        </nav>
      </header>
      <div className="feed-page">
        <div className="left-content">
          {isLoading && !feedData ? (
            <div>Loading Profile...</div>
          ) : feedData?.profile_sidebar ? (
            <aside className="profile-card">
              <div
                className="profile-header"
                style={{
                  backgroundImage: `url('${feedData.profile_sidebar.cover_photo || '/images/cvr.jpg'}')`,
                }}
              >
                <img src={feedData.profile_sidebar.profile_photo || "/images/prof.jpg"} alt="" />
              </div>
              <div className="profile-body pad">
                <div className="namee-row cntr">
                  <h4
                    className="name hd"
                    onClick={() => router.push("/profile-page")}
                    style={{ cursor: "pointer" }}
                  >
                    {feedData.profile_sidebar.full_name}
                  </h4>
                  {feedData.profile_sidebar.verified && (
                    <img
                      src="/images/icons/vrfd.svg"
                      alt="verified-tag"
                      className="vrfd-tg"
                    />
                  )}
                </div>
                <p className="subttl">
                  {feedData.profile_sidebar.designation || ""}
                  <br />
                  {feedData.profile_sidebar.finalEducation || ""}
                </p>

                <div className="profile-stats">
                  <div>
                    <span>
                      <h3>Publications</h3>
                    </span>
                    <span>{feedData.profile_sidebar.publications_count || 0}</span>
                  </div>
                  <div>
                    <span>
                      <h3>h-index</h3>
                    </span>
                    <span>{feedData.profile_sidebar.h_index || 0}</span>
                  </div>
                  <div>
                    <span>
                      <h3>Followers</h3>
                    </span>
                    <span>{feedData.profile_sidebar.followers_count || 0}</span>
                  </div>
                </div>

                <div className="profile-tags">
                  <span>{feedData.profile_sidebar.domain_classification?.[0] || 'Domain'}</span>
                  <span>Current Affiliations: {feedData.profile_sidebar.affiliations_count || 0}</span>
                  <HiOutlineDotsHorizontal className="dots-icon" />
                </div>

                {feedData.profile_sidebar.domain_classification && (
                  <div className="profile-section">
                    <h3>Domain & Classification:</h3>
                    <p>
                      {feedData.profile_sidebar.domain_classification.join(", ")}
                    </p>
                  </div>
                )}

                {feedData.profile_sidebar.research_interests && (
                  <div className="profile-section">
                    <h3>Research Interests:</h3>
                    <p>
                      {feedData.profile_sidebar.research_interests.join(", ")}
                    </p>
                  </div>
                )}
              </div>
            </aside>
          ) : null}
        </div>
        <div className="feed-content">
          {/* HEADER */}
          <div className="feed-header form-header">
            <div style={{ width: '100%', display: 'flex', gap: '10px' }}>
              <input
                type="text"
                placeholder="What's on your mind?"
                value={postText}
                onChange={(e) => setPostText(e.target.value)}
                style={{ flex: 1, padding: '10px', borderRadius: '5px', border: '1px solid #ccc' }}
              />
              <button
                onClick={handleCreatePost}
                className="read-more crv"
                disabled={isPosting || !postText.trim()}>
                {isPosting ? 'Posting...' : 'Post'}
              </button>
            </div>
          </div>
          {/* 🔹 DYNAMIC FEED CARDS */}
          {isLoading && !feedData ? (
            <p style={{ textAlign: "center", marginTop: "20px" }}>Loading feed...</p>
          ) : error ? (
            <p style={{ textAlign: "center", color: "red", marginTop: "20px" }}>{error}</p>
          ) : (
            <>
              {posts.map((item) => (
                <div className="feed-card" key={item.post_id || (item as any).id}>
                  <div className="feed-top">
                    <div className="feed-user">
                      <img src={item.author_photo || "https://randomuser.me/api/portraits/lego/1.jpg"} alt={item.author_name} />
                      <div style={{ display: "flex", flexDirection: "column" }}>
                        <span>{item.author_name}</span>
                        <small style={{ color: "#888", fontSize: "12px" }}>{moment(item.created_at).fromNow()}</small>
                      </div>
                    </div>
                    <HiOutlineDotsHorizontal className="dots-icon" />
                  </div>

                  <p className="feed-text">{item.post_text}</p>

                  {/* IMAGES (Conditional) */}
                  {item.media_urls && item.media_urls.length > 0 && (
                    <div className="feed-immg">
                      {item.media_urls.map((img, i) => (
                        <img key={i} src={img} className="feed-img sm" alt="Post Request Media" />
                      ))}
                    </div>
                  )}

                  {/* ACTIONS */}
                  <div className="feed-actions-row">
                    <div className="left-icn">
                      <span
                        onClick={() => toggleLike(item.post_id || (item as any).id)}
                        style={{ cursor: "pointer", display: "flex", alignItems: "center", gap: "5px", color: item.is_liked ? "red" : "inherit" }}
                      >
                        <Image
                          src={item.is_liked ? "/images/icons/hrt-filled.svg" : "/images/icons/hrt.svg"}
                          alt="Like"
                          width={15}
                          height={15}
                          style={item.is_liked ? { filter: "invert(20%) sepia(85%) saturate(7000%) hue-rotate(350deg) brightness(100%) contrast(100%)" } : {}}
                        />
                        {item.like_count > 0 && <span>{item.like_count}</span>}
                      </span>
                      <span style={{ cursor: "pointer", display: "flex", alignItems: "center", gap: "5px" }}>
                        <Image
                          src="/images/icons/cht.svg"
                          alt="Comment"
                          width={15}
                          height={15}
                        />
                        {item.comment_count > 0 && <span>{item.comment_count}</span>}
                      </span>
                      <span>
                        <Image
                          src="/images/icons/shr.svg"
                          alt="Share"
                          width={15}
                          height={15}
                        />
                        {item.share_count > 0 && <span>{item.share_count}</span>}
                      </span>
                    </div>
                    <span>
                      <Image
                        src="/images/icons/wslst.svg"
                        alt="Save"
                        width={15}
                        height={15}
                      />
                    </span>
                  </div>
                </div>
              ))}
              {/* Infinite Scroll trigger target */}
              {hasMore && (
                <div ref={lastPostElementRef} style={{ height: "20px", background: "transparent" }}>
                  {isFetchingMore && <p style={{ textAlign: "center" }}>Loading older posts...</p>}
                </div>
              )}
            </>
          )}
        </div>
        <div className="right-content">
          <div className="side-card artl-card">
            <h4 className="side-title">SUGGESTED ARTICLE / BLOG</h4>
            {feedData?.suggested_articles && feedData.suggested_articles.length > 0 ? (
              feedData.suggested_articles.slice(0, 3).map((article) => (
                <div className="article-item sm" key={article.article_id}>
                  <img src={article.article_thumbnail || "https://images.unsplash.com/photo-1503676260728-1c00da094a0b"} alt="article thumb" />
                  <div>
                    <span className="tag orange">{article.article_category || "ARTICLE"}</span>
                    <p>{article.article_title}</p>
                    <small>{moment(article.published_time).format("MMMM D · h:mm a")}</small>
                  </div>
                </div>
              ))
            ) : (
              <p style={{ padding: '10px' }}>No suggested articles right now.</p>
            )}
            {feedData?.suggested_articles && feedData.suggested_articles.length > 3 && (
              <button className="read-more crv">READ MORE</button>
            )}
          </div>
          {/* <!-- POST ACTIVITY --> */}
          <div className="side-card activity-card">
            <div className="side-headerpst">
              <h4>POST ACTIVITY</h4>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>

            {feedData?.post_activities && feedData.post_activities.length > 0 ? (
              feedData.post_activities.slice(0, 3).map((activity) => (
                <div className="activity-item" key={activity.activity_id}>
                  <img src={activity.activity_thumbnail || "https://randomuser.me/api/portraits/lego/1.jpg"} alt="activity thumb" />
                  <span>{activity.activity_title}</span>
                  <div className="right-ico">
                    <span>
                      <FaRegEye />
                    </span>
                    <b>{activity.view_count.toLocaleString()}</b>
                  </div>
                </div>
              ))
            ) : (
              <p style={{ padding: '10px' }}>No recent post activity.</p>
            )}

            {feedData?.post_activities && feedData.post_activities.length > 3 && (
              <button className="read-more crv">SEE MORE</button>
            )}
          </div>
          {/* <!-- NOTABLE --> */}
          <div className="side-card notable-card">
            <div className="side-headerpst">
              <h4>NOTABLE</h4>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>
            {feedData?.notable && feedData.notable.length > 0 ? (
              <Carousel
                indicators={false}
                controls={true}
                interval={null}
                className="notable-carousel"
              >
                {/** Split into chunks of 3 for the carousel items */}
                {Array.from({ length: Math.ceil(feedData.notable.length / 3) }).map((_, i) => (
                  <Carousel.Item key={i}>
                    <div className="notable-row">
                      {feedData.notable?.slice(i * 3, i * 3 + 3).map((person) => (
                        <div className="notable-user" key={person.user_id || person.notable_id}>
                          <img src={person.profile_photo || "https://randomuser.me/api/portraits/lego/2.jpg"} alt={person.name} />
                          <p>{person.name}</p>
                          <span>{person.role || "Researcher"}</span>
                          {person.email && <p className="sub" style={{ wordBreak: 'break-all' }}>{person.email}</p>}
                        </div>
                      ))}
                    </div>
                  </Carousel.Item>
                ))}
              </Carousel>
            ) : (
              <p style={{ padding: '10px', textAlign: 'center' }}>No notable profiles.</p>
            )}
            <button className="read-more crv">SEE MORE</button>
          </div>
          <section className="side-card suggst-section">
            <h4 className="resrch-titl-left sm">YOU MAY LIKE</h4>
            <p className="subb">Pages for you</p>
            <div className="suggest-list">
              <div className="suggest-item">
                <div className="suggest-left">
                  <img
                    src="/images/scigrp.jpg"
                    className="suggest-avatar-img"
                  />
                  <span>Science Group</span>
                </div>
                <button className="follow-btn">
                  <FaUserPlus /> Follow
                </button>
              </div>
              <div className="suggest-item">
                <div className="suggest-left">
                  <img
                    src="https://randomuser.me/api/portraits/men/40.jpg"
                    className="suggest-avatar-img"
                  />
                  <span>Research Group</span>
                </div>
                <button className="follow-btn">
                  <FaUserPlus /> Follow
                </button>
              </div>
            </div>
          </section>
        </div>
      </div>
      {/* <footer className="site-footer">
        <div className="footer-top">
          <div className="footer-left">
            <h3 className="footer-logo">ResearchCrest</h3>
            <p>
              Stay in the know by subscribing to our
              <br />
              newsletter below
            </p>

            <div className="newsletter">
              <input type="email" placeholder="Enter your email address" />
              <button>→</button>
            </div>
          </div>

          <div className="footer-right">
            <div className="footer-col">
              <h4>Contact</h4>
              <a href="#">Contact Form</a>
              <a href="#">FAQ</a>
              <a href="#">Privacy Policy</a>
              <a href="#">T&amp;C</a>
            </div>

            <div className="footer-col">
              <h4>Social</h4>
              <a href="#">Facebook</a>
              <a href="#">Youtube</a>
              <a href="#">Twitter</a>
              <a href="#">LinkedIn</a>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <span>© Researchcrest. All Rights Reserved 2023</span>
          <span>Terms &amp; Conditions</span>
        </div>
      </footer> */}
    </>
  );
}
