import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { TbGridDots } from "react-icons/tb";
import { IoNotifications } from "react-icons/io5";
import { IoIosArrowDown } from "react-icons/io";
import { HiOutlineDotsHorizontal } from "react-icons/hi";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function FeediPage() {
  const router = useRouter();
  useEffect(() => {
    document.body.classList.add("feed-body");
    return () => {
      document.body.classList.remove("feed-body");
    };
  }, []);
  return (
    <>
      <Head>
        <title>ResearchCrest – Feedi Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
      </Head>
      <header className="fnav">
        <div className="logo">
          <Image
            src="/logo.svg"
            alt="ResearchCrest Logo"
            width={160}
            height={40}
            priority
          />
        </div>
        <div className="search">
          <input type="text" placeholder="Search In Research Crest" />
        </div>
        <nav className="feed-menu">
          <a>Home</a>
          <a>Q&amp;A</a>
          <a>Network</a>
          <a>career</a>
          <a>Scholarship</a>
          <a href="#" className="nine-dots">
            <TbGridDots
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.2rem",
                color: "#000",
              }}
            />
          </a>
          <a>
            <IoNotifications
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.2rem",
                color: "#000",
              }}
            />
          </a>
          <a className="profile-wrapper">
            <img
              src="https://randomuser.me/api/portraits/men/32.jpg"
              alt=""
              className="menu-logo"
            />
            <IoIosArrowDown className="arrow-icon" />
          </a>
        </nav>
      </header>
      <div className="feed-page">
        <div className="left-content">
          <aside className="profile-card">
            <div className="profile-header">
              <img
                src="https://randomuser.me/api/portraits/men/32.jpg"
                alt=""
              />
            </div>

            <div className="profile-body">
              <h3
                onClick={() => router.push("/profile-page")}
                style={{ cursor: "pointer" }}
              >
                Brand Gardner
              </h3>

              <p className="subtitle">
                Assistant General Manager - HR | Business HR & Strategy
                <br />
                MHRM (University of London)
              </p>

              <div className="profile-stats">
                <div>
                  <span>Publications</span>
                  <strong>42</strong>
                </div>
                <div>
                  <span>h-index</span>
                  <strong>18</strong>
                </div>
                <div>
                  <span>Followers</span>
                  <strong>324</strong>
                </div>
              </div>

              <div className="profile-tags">
                <span>CSE</span>
                <span>Current Affiliations: 50</span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </div>

              <div className="profile-section">
                <h4>Domain & Classification:</h4>
                <p>
                  Electrical Engineering
                  <br />
                  Faculty of Technology
                  <br />
                  Advance Polymers and Composite Research Group
                </p>
              </div>

              <div className="profile-section">
                <h4>Research Interests:</h4>
                <p>
                  Renewable Energy,
                  <br />
                  Internet of Things,
                  <br />
                  Machine Learning
                </p>
              </div>

              <div className="profile-section">
                <h4>Advisors:</h4>
                <p className="green">
                  Dr. Emily Carter
                  <br />
                  Dr. Steven Harris
                </p>
              </div>

              <div className="profile-section">
                <h4>MS Advisors:</h4>
                <p className="green">
                  Prof. Dr. Jonathan Miles
                  <br />
                  Prof. Dr. Rebecca Thornton
                </p>
              </div>

              <div className="profile-section">
                <h4>Responsibilities:</h4>
                <ul>
                  <li>
                    Introduction to Materials and Manufacture (Module
                    Co-ordinator)
                  </li>
                  <li>Materials and Manufacture</li>
                  <li>Sustainable Development and Environmental Management</li>
                  <li>
                    Design and Sustainable Development (Distance Learning
                    Module, Module-Coordinator)
                  </li>
                </ul>
              </div>
            </div>
          </aside>
          <div className="side-card article-card">
            <h4 className="side-title">SUGGESTED ARTICLE / BLOG</h4>

            <div className="article-item">
              <img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b" />
              <div>
                <span className="tag orange">EDUCATION</span>
                <p>
                  In an era of budget cuts, funding for science and research is
                  being slashed
                </p>
                <small>August 22 · 8:48 pm</small>
              </div>
            </div>

            <div className="article-item">
              <img src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d" />
              <div>
                <span className="tag green">SOCIETY</span>
                <p>
                  The Safety Council has issued the following news release
                  regarding…
                </p>
                <small>August 22 · 8:40 pm</small>
              </div>
            </div>

            <button className="read-more">
              READ MORE ON REALLYGREATSITE.COM
            </button>
          </div>
        </div>
        <div className="feed-content">
          <div className="feed-header">
            <input type="text" placeholder="Search" />
            <div className="feed-actions">
              <span>📷</span>
              <span>🖼️</span>
              <span>📄</span>
              <span className="send">✈️</span>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/women/44.jpg" />
                <span>Railly Watson</span>
              </div>
              <span>•••</span>
            </div>
            <p className="feed-text">
              Golden, comforting, and irresistibly flavorful—this dish is a
              celebration of taste and tradition. Each bite delivers a perfect
              balance of rich spices, fresh ingredients, and slow-cooked
              goodness that warms both the heart and soul. The aroma alone is
              enough to awaken your appetite, drawing you into a moment of pure
              indulgence.
            </p>
            <img
              className="feed-img"
              src="https://images.unsplash.com/photo-1512621776951-a57141f2eefd"
            />

            <div className="feed-actions-row">
              <span>❤️</span>
              <span>💬</span>
              <span>📤</span>
              <span className="save">🔖</span>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/men/33.jpg" />
                <span>James Garry</span>
              </div>
              <span>•••</span>
            </div>

            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non
              diam eleifend, imperdiet orci nec.
            </p>

            <div className="feed-actions-row">
              <span>❤️</span>
              <span>💬</span>
              <span>📤</span>
              <span className="save">🔖</span>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/men/31.jpg" />
                <span>Sam Stain</span>
              </div>
              <span>•••</span>
            </div>
            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
              malesuada magna orci, in vestibulum turpis scelerisque vitae.
            </p>
            <img
              className="feed-img"
              src="https://images.unsplash.com/photo-1501785888041-af3ef285b470"
            />
            <div className="feed-actions-row">
              <span>❤️</span>
              <span>💬</span>
              <span>📤</span>
              <span className="save">🔖</span>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/women/43.jpg" />
                <span>Luna Rodrigage</span>
              </div>
              <span>•••</span>
            </div>
            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non
              diam eleifend, imperdiet orci nec.
            </p>
            <div className="feed-actions-row">
              <span>❤️</span>
              <span>💬</span>
              <span>📤</span>
              <span className="save">🔖</span>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/women/42.jpg" />
                <span>Naomi Watts</span>
              </div>
              <span>•••</span>
            </div>
            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
              malesuada magna orci, in vestibulum turpis scelerisque vitae.
            </p>
            <img
              className="feed-img"
              src="https://images.unsplash.com/photo-1470770841072-f978cf4d019e"
            />

            <div className="feed-actions-row">
              <span>❤️</span>
              <span>💬</span>
              <span>📤</span>
              <span className="save">🔖</span>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/women/40.jpg" />
                <span>Korey Jackson</span>
              </div>
              <span>•••</span>
            </div>

            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non
              diam eleifend, imperdiet orci nec.
            </p>

            <div className="feed-actions-row">
              <span>❤️</span>
              <span>💬</span>
              <span>📤</span>
              <span className="save">🔖</span>
            </div>
          </div>
        </div>
        <div className="right-content">
          <aside className="right-bar">
            <div className="side-card">
              <h4>SUGGESTED ARTICLE / BLOG</h4>

              <div className="article">
                <img src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d" />
                <p>The company also recently announced a quarterly dividend.</p>
              </div>

              <div className="article">
                <img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b" />
                <p>Film festival says culture no longer a commodity.</p>
              </div>
            </div>
          </aside>
          {/* <!-- POST ACTIVITY --> */}
          <div className="side-card activity-card">
            <div className="side-header">
              <h4>Post Activity</h4>
              <span>•••</span>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/women/12.jpg" />
              <span>My Wedding Celebration</span>
              <b>7,890</b>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/men/44.jpg" />
              <span>Christmas Celebration</span>
              <b>7,890</b>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/women/32.jpg" />
              <span>My Graduation</span>
              <b>7,890</b>
            </div>
          </div>
          {/* <!-- NOTABLE --> */}
          <div className="side-card notable-card">
            <div className="side-header">
              <h4>Notable</h4>
              <span>•••</span>
            </div>

            <div className="notable-row">
              <div className="notable-user">
                <img src="https://randomuser.me/api/portraits/men/45.jpg" />
                <p>Alfredo</p>
                <span>Professor</span>
              </div>

              <div className="notable-user">
                <img src="https://randomuser.me/api/portraits/women/52.jpg" />
                <p>Cahaya</p>
                <span>Teacher</span>
              </div>

              <div className="notable-user">
                <img src="https://randomuser.me/api/portraits/women/68.jpg" />
                <p>Mariana</p>
                <span>Student</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* <footer className="site-footer">
        <div className="footer-top">
          <div className="footer-left">
            <h3 className="footer-logo">ResearchCrest</h3>
            <p>
              Stay in the know by subscribing to our
              <br />
              newsletter below
            </p>

            <div className="newsletter">
              <input type="email" placeholder="Enter your email address" />
              <button>→</button>
            </div>
          </div>

          <div className="footer-right">
            <div className="footer-col">
              <h4>Contact</h4>
              <a href="#">Contact Form</a>
              <a href="#">FAQ</a>
              <a href="#">Privacy Policy</a>
              <a href="#">T&amp;C</a>
            </div>

            <div className="footer-col">
              <h4>Social</h4>
              <a href="#">Facebook</a>
              <a href="#">Youtube</a>
              <a href="#">Twitter</a>
              <a href="#">LinkedIn</a>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <span>© Researchcrest. All Rights Reserved 2023</span>
          <span>Terms &amp; Conditions</span>
        </div>
      </footer> */}
    </>
  );
}
