import { useRouter } from "next/router";
import {
  useEffect,
  //useRef
} from "react";
import Head from "next/head";
import Image from "next/image";
import { Carousel } from "react-bootstrap";
import { TbGridDots } from "react-icons/tb";
import { IoMdNotificationsOutline } from "react-icons/io";
import { IoIosArrowDown } from "react-icons/io";
import { HiOutlineDotsHorizontal } from "react-icons/hi";
import { IoMdSearch } from "react-icons/io";
import { Geist, Geist_Mono } from "next/font/google";
import { IoIosArrowBack, IoIosArrowForward } from "react-icons/io";
import { FaRegEye } from "react-icons/fa";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function PrevArrow(props: any) {
  const { onClick } = props;
  return (
    <span className="slider-arrow left" onClick={onClick}>
      <IoIosArrowBack />
    </span>
  );
}

function NextArrow(props: any) {
  const { onClick } = props;
  return (
    <span className="slider-arrow right" onClick={onClick}>
      <IoIosArrowForward />
    </span>
  );
}

export default function FeedPage() {
  const router = useRouter();
  useEffect(() => {
    document.body.classList.add("feed-body");
    return () => {
      document.body.classList.remove("feed-body");
    };
  }, []);
  return (
    <>
      <Head>
        <title>ResearchCrest – Feed Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
      </Head>
      <header className="fnav">
        <div className="logo">
          <Image
            src="/logo.svg"
            alt="ResearchCrest Logo"
            width={160}
            height={40}
            priority
          />
        </div>
        <div className="search">
          <input type="text" placeholder="Search In Research Crest" />
        </div>
        <nav className="feed-menu">
          <a>Home</a>
          <a>Q&amp;A</a>
          <a>Network</a>
          <a>career</a>
          <a>Scholarship</a>
          <a href="#" className="nine-dots">
            <TbGridDots
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.2rem",
                color: "#000",
              }}
            />
          </a>
          <a>
            <IoMdNotificationsOutline
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.3rem",
                color: "#000",
              }}
            />
          </a>
          <a className="profile-wrapper">
            <img
              src="https://randomuser.me/api/portraits/men/32.jpg"
              alt=""
              className="menu-logo"
            />
            <IoIosArrowDown className="arrow-icon" />
          </a>
        </nav>
      </header>
      <div className="feed-page">
        <div className="left-content">
          <aside className="profile-card">
            <div
              className="profile-header"
              style={{
                backgroundImage:
                  "url('https://images.unsplash.com/photo-1467269204594-9661b134dd2b')",
              }}
            >
              <img
                src="https://randomuser.me/api/portraits/men/32.jpg"
                alt=""
              />
            </div>
            <div className="profile-body">
              <h4
                onClick={() => router.push("/profile-page")}
                style={{ cursor: "pointer" }}
              >
                Brand Gardner
              </h4>
              <p className="subttl">
                Assistant General Manager - HR | Business HR & Strategy
                <br />
                MHRM (University of London)
              </p>

              <div className="profile-stats">
                <div>
                  <span>
                    <h3>Publications</h3>
                  </span>
                  <span>42</span>
                </div>
                <div>
                  <span>
                    <h3>h-index</h3>
                  </span>
                  <span>18</span>
                </div>
                <div>
                  <span>
                    <h3>Followers</h3>
                  </span>
                  <span>324</span>
                </div>
              </div>

              <div className="profile-tags">
                <span>CSE</span>
                <span>Current Affiliations: 50</span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </div>
            </div>
          </aside>
          <aside className="profile-card">
            <div className="p-body">
              <div className="profile-section">
                <h3>Domain & Classification:</h3>
                <p>
                  Electrical Engineering
                  <br />
                  Faculty of Technology
                  <br />
                  Advance Polymers and Composite Research Group
                </p>
              </div>

              <div className="profile-section">
                <h3>Research Interests:</h3>
                <p>
                  Renewable Energy,
                  <br />
                  Internet of Things,
                  <br />
                  Machine Learning
                </p>
              </div>
              <div className="profile-section">
                <h3>Advisors:</h3>
                <p className="green">
                  Dr. Emily Carter
                  <br />
                  Dr. Steven Harris
                </p>
              </div>

              <div className="profile-section">
                <h3>MS Advisors:</h3>
                <p className="green">
                  Prof. Dr. Jonathan Miles
                  <br />
                  Prof. Dr. Rebecca Thornton
                </p>
              </div>

              <div className="profile-section">
                <h3>Responsibilities:</h3>
                <ul>
                  <li>
                    Introduction to Materials and Manufacture (Module
                    Co-ordinator)
                  </li>
                  <li>Materials and Manufacture</li>
                  <li>Sustainable Development and Environmental Management</li>
                  <li>
                    Design and Sustainable Development (Distance Learning
                    Module, Module-Coordinator)
                  </li>
                </ul>
              </div>
            </div>
          </aside>
        </div>
        <div className="feed-content">
          {/* <div className="feed-header">
            <input type="text" placeholder="Search" />
            <div className="feed-actions">
              <span>
                <IoMdSearch className="dots-icon" />
              </span>
              <span>📷</span>
              <span>🖼️</span>
              <span>📄</span>
            </div>
          </div> */}
          <div className="feed-header">
            <div>
              {/* <input type="text" placeholder="Search" /> */}
              <IoMdSearch className="sch-icon" />
              <div className="feed-actions">
                <span>
                  <Image
                    src="/images/icons/srch.svg"
                    alt="Search Icon"
                    width={45}
                    height={45}
                    priority
                    className="srchbr-icn"
                  />
                </span>
              </div>
            </div>
            <div>
              <span className="icn">
                <Image
                  src="/images/icons/ply.svg"
                  alt=""
                  width={45}
                  height={45}
                  className="srchbr-icn"
                />
              </span>
              <span className="icn">
                <Image
                  src="/images/icons/phto.svg"
                  alt=""
                  width={45}
                  height={45}
                  className="srchbr-icn"
                />
              </span>
              <span className="icn">
                <Image
                  src="/images/icons/ppr.svg"
                  alt=""
                  width={45}
                  height={45}
                  className="srchbr-icn"
                />
              </span>
            </div>
          </div>
          <div className="ffeed-card">
            <div className="ffeed-top">
              <div className="ffeed-user">
                <img src="https://randomuser.me/api/portraits/women/44.jpg" />
                <span>Railly Watson</span>
              </div>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>
            <div>
            <img
              className="feed-img"
              src="https://images.unsplash.com/photo-1512621776951-a57141f2eefd"
            />
            </div>
            <p className="feed-text">
              Golden, comforting, and irresistibly flavorful—this dish is a
              celebration of taste and tradition. Each bite delivers a perfect
              balance of rich spices, fresh ingredients, and slow-cooked
              goodness that warms both the heart and soul. The aroma alone is
              enough to awaken your appetite, drawing you into a moment of pure
              indulgence.
            </p>
            <div className="feed-actions-row">
              <div className="left-icn">
                <span>
                  <Image
                    src="/images/icons/hrt.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/cht.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/shr.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
              <div>
                <span>
                  <Image
                    src="/images/icons/wslst.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/men/33.jpg" />
                <span>James Garry</span>
              </div>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>
            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non
              diam eleifend, imperdiet orci nec.
            </p>

            <div className="feed-actions-row">
              <div className="left-icn">
                <span>
                  <Image
                    src="/images/icons/hrt.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/cht.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/shr.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
              <div>
                <span>
                  <Image
                    src="/images/icons/wslst.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/men/31.jpg" />
                <span>Sam Stain</span>
              </div>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>
            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
              malesuada magna orci, in vestibulum turpis scelerisque vitae.
            </p>
            <img
              className="feed-img"
              src="https://images.unsplash.com/photo-1501785888041-af3ef285b470"
            />
            <div className="feed-actions-row">
              <div className="left-icn">
                <span>
                  <Image
                    src="/images/icons/hrt.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/cht.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/shr.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
              <div>
                <span>
                  <Image
                    src="/images/icons/wslst.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/women/43.jpg" />
                <span>Luna Rodrigage</span>
              </div>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>
            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non
              diam eleifend, imperdiet orci nec.
            </p>
            <div className="feed-actions-row">
              <div className="left-icn">
                <span>
                  <Image
                    src="/images/icons/hrt.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/cht.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/shr.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
              <div>
                <span>
                  <Image
                    src="/images/icons/wslst.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/women/42.jpg" />
                <span>Naomi Watts</span>
              </div>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>
            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
              malesuada magna orci, in vestibulum turpis scelerisque vitae.
            </p>
            <img
              className="feed-img"
              src="https://images.unsplash.com/photo-1470770841072-f978cf4d019e"
            />

            <div className="feed-actions-row">
              <div className="left-icn">
                <span>
                  <Image
                    src="/images/icons/hrt.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/cht.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/shr.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
              <div>
                <span>
                  <Image
                    src="/images/icons/wslst.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
            </div>
          </div>
          <div className="feed-card">
            <div className="feed-top">
              <div className="feed-user">
                <img src="https://randomuser.me/api/portraits/women/40.jpg" />
                <span>Korey Jackson</span>
              </div>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>

            <p className="feed-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non
              diam eleifend, imperdiet orci nec.
            </p>

            <div className="feed-actions-row">
              <div className="left-icn">
                <span>
                  <Image
                    src="/images/icons/hrt.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/cht.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
                <span>
                  <Image
                    src="/images/icons/shr.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
              <div>
                <span>
                  <Image
                    src="/images/icons/wslst.svg"
                    alt=""
                    width={15}
                    height={15}
                  />
                </span>
              </div>
            </div>
          </div>
        </div>
        <div className="right-content">
          <div className="side-card article-card">
            <h4 className="side-title">SUGGESTED ARTICLE / BLOG</h4>

            <div className="article-item">
              <img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b" />
              <div>
                <span className="tag orange">EDUCATION</span>
                <p>
                  In an era of budget cuts, funding for science and research is
                  being slashed
                </p>
                <small>August 22 · 8:48 pm</small>
              </div>
            </div>

            <div className="article-item">
              <img src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d" />
              <div>
                <span className="tag green">SOCIETY</span>
                <p>
                  The Safety Council has issued the following news release
                  regarding…
                </p>
                <small>August 22 · 8:40 pm</small>
              </div>
            </div>

            <button className="read-more">READ MORE</button>
          </div>
          {/* <!-- POST ACTIVITY --> */}
          <div className="side-card activity-card">
            <div className="side-header">
              <h4>POST ACTIVITY</h4>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/women/12.jpg" />
              <span>My Wedding Celebration</span>
              <div className="right-ico">
                <span>
                  <FaRegEye />
                </span>
                <b>7,890</b>
              </div>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/men/44.jpg" />
              <span>Christmas Celebration</span>
              <div className="right-ico">
                <span>
                  <FaRegEye />
                </span>
                <b>600</b>
              </div>
            </div>

            <div className="activity-item">
              <img src="https://randomuser.me/api/portraits/women/32.jpg" />
              <span>My Graduation</span>
              <div className="right-ico">
                <span>
                  <FaRegEye />
                </span>
                <b>390</b>
              </div>
            </div>
            <button className="read-more">SEE MORE</button>
          </div>
          {/* <!-- NOTABLE --> */}
          <div className="side-card notable-card">
            <div className="side-header">
              <h4>NOTABLE</h4>
              <span>
                <HiOutlineDotsHorizontal className="dots-icon" />
              </span>
            </div>
            <Carousel
              indicators={false}
              controls={true}
              interval={null}
              className="notable-carousel"
            >
              <Carousel.Item>
                <div className="notable-row">
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/men/45.jpg" />
                    <p>Alfredo</p>
                    <span>Professor</span>
                    <p className="sub">alfredo@gmail.com</p>
                  </div>
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/women/52.jpg" />
                    <p>Cahaya</p>
                    <span>Teacher</span>
                    <p>cahaya@gmail.com</p>
                  </div>
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/women/68.jpg" />
                    <p>Mariana</p>
                    <span>Student</span>
                    <p>mariana@gmail.com</p>
                  </div>
                </div>
              </Carousel.Item>
              <Carousel.Item>
                <div className="notable-row">
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/men/46.jpg" />
                    <p>James</p>
                    <span>Professor</span>
                    <p className="sub">alfredo@gmail.com</p>
                  </div>
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/women/53.jpg" />
                    <p>Susan</p>
                    <span>Teacher</span>
                    <p>susan@gmail.com</p>
                  </div>
                  <div className="notable-user">
                    <img src="https://randomuser.me/api/portraits/women/69.jpg" />
                    <p>Linda</p>
                    <span>Student</span>
                    <p>linda@gmail.com</p>
                  </div>
                </div>
              </Carousel.Item>
            </Carousel>
            <button className="read-more">SEE MORE</button>
          </div>
        </div>
      </div>
      {/* <footer className="site-footer">
        <div className="footer-top">
          <div className="footer-left">
            <h3 className="footer-logo">ResearchCrest</h3>
            <p>
              Stay in the know by subscribing to our
              <br />
              newsletter below
            </p>

            <div className="newsletter">
              <input type="email" placeholder="Enter your email address" />
              <button>→</button>
            </div>
          </div>

          <div className="footer-right">
            <div className="footer-col">
              <h4>Contact</h4>
              <a href="#">Contact Form</a>
              <a href="#">FAQ</a>
              <a href="#">Privacy Policy</a>
              <a href="#">T&amp;C</a>
            </div>

            <div className="footer-col">
              <h4>Social</h4>
              <a href="#">Facebook</a>
              <a href="#">Youtube</a>
              <a href="#">Twitter</a>
              <a href="#">LinkedIn</a>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <span>© Researchcrest. All Rights Reserved 2023</span>
          <span>Terms &amp; Conditions</span>
        </div>
      </footer> */}
    </>
  );
}
