// import Head from "next/head";
// import Image from "next/image";
// import { TbGridDots } from "react-icons/tb";
// import { useRouter } from "next/router";
// import { useState, useRef, useEffect } from "react";
// export default function Index() {
//   const router = useRouter();
//   const [email, setEmail] = useState("");
//   const [password, setPassword] = useState("");
//   const [open, setOpen] = useState(false);
//   const dropdownRef = useRef<HTMLDivElement>(null);
//   const handleLogin = () => {
//     if (email === "brand@gmail.com" && password === "12345678") {
//       router.push("/feed-page");
//     } else {
//       alert("Invalid email or password");
//     }
//   };
//   useEffect(() => {
//     const handleClickOutside = (event: MouseEvent) => {
//       if (
//         dropdownRef.current &&
//         !dropdownRef.current.contains(event.target as Node)
//       ) {
//         setOpen(false);
//       }
//     };

//     document.addEventListener("mousedown", handleClickOutside);
//     return () => document.removeEventListener("mousedown", handleClickOutside);
//   }, []);

//   return (
//     <>
//       <Head>
//         <title>TensorCrest – Index Page</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" type="image/svg+xml" href="/logo.svg" />
//       </Head>
//       <header className="navbar-main">
//         <div className="logo">
//           <Image
//             src="/logo.svg"
//             alt="ResearchCrest Logo"
//             width={160}
//             height={40}
//             priority
//           />
//         </div>
//         <nav className="nn-nav">
//           <a href="#">App</a>
//           <a href="#">Join</a>
//           <a href="#">Sign in</a>
//           <a href="#">Help Center</a>
//           {/* <a href="#" className="nine-dots">
//             <TbGridDots
//               style={{
//                 verticalAlign: "middle",
//                 marginLeft: "6px",
//                 fontSize: "1.2rem",
//               }}
//             />
//           </a> */}
//           {/* Nine Dots */}
//           <div className="ninn-dots-wrapper" ref={dropdownRef}>
//             <TbGridDots className="ninn-dots-icon"
//               onClick={() => setOpen(!open)}
//             />
//             {/* Dropdown */}
//             {open && (
//               <div className="nn-dropdown">
//                 <div className="nn-dropdown-left">
//                   <h4>My Apps</h4>
//                   <a href="#">Find New Clients</a>
//                   <a href="#">Groups</a>
//                   <a href="#">Manage Billing</a>

//                   <h4>Talent</h4>
//                   <a href="#">Hire with AI</a>
//                   <a href="#">Talent Insights</a>

//                   <h4>Sales</h4>
//                   <a href="#">Services Marketplace</a>
//                 </div>
//                 <div className="nn-dropdown-right">
//                   <h4>Explore more for business</h4>
//                   <a href="#">Hire on TensorCrest</a>
//                   <a href="#">Sell with TensorCrest</a>
//                   <a href="#">Post a job</a>
//                   <a href="#">Advertise</a>
//                   <a href="#">Get Premium</a>
//                   <a href="#">Admin Center</a>
//                 </div>
//               </div>
//             )}
//           </div>
//         </nav>
//       </header>
//       <section className="i-hero">
//         <div className="i-hero-left">
//           <h1>
//             “Research with Purpose.
//             <br />
//             Impact with Vision.”
//           </h1>

//           <p>
//             Ready-to-use placeholder text for a researcher website’s i-hero
//             section.
//           </p>

//           <div className="stats pro">
//             <div>
//               <strong>3M+</strong>
//               <span>Profiles</span>
//             </div>
//             <div>
//               <strong>10M+</strong>
//               <span>Visitors</span>
//             </div>
//             <div>
//               <strong>1M+</strong>
//               <span>Industry Experts</span>
//             </div>
//             <div>
//               <strong>2M+</strong>
//               <span>Audience</span>
//             </div>
//           </div>

//           <div className="i-hero-buttons">
//             <button className="btn primary">Register Now</button>
//             <button className="btn secondary">Learn More</button>
//           </div>
//         </div>

//         <div className="i-hero-right">
//           <div className="login-card">
//             <h2>Welcome to ResearchCrest</h2>
//             <label>Email or Phone</label>
//             <input type="text"
//               placeholder="you@example.com"
//               value={email}
//               onChange={(e) => setEmail(e.target.value)}
//             />

//             <label>Password</label>
//             <input type="password"
//               placeholder="••••••••"
//               value={password}
//               onChange={(e) => setPassword(e.target.value)}
//             />

//             <button className="login-btn"
//               onClick={handleLogin}
//             >🔒 Log in</button>

//             <div className="login-links">
//               <a href="#">Forgot password?</a>
//               <a href="#">Create new account</a>
//             </div>
//           </div>
//         </div>
//       </section>
//       <section className="research-features">
//         <h2>
//           Research <span>Features</span>
//         </h2>
//         <div className="features-layout">
//           <div className="features-col">
//             <div className="feature-card teal-bar">
//               <h4>Performance graph and cart</h4>
//               <p>
//                 Track delivery, quality, and reliability metrics on a consistent
//                 basis.
//               </p>
//             </div>

//             <div className="feature-card dark-bar">
//               <h4>AI chatbot and timeline</h4>
//               <p>
//                 Continue or formally end the partnership based on overall
//                 performance.
//               </p>
//             </div>
//           </div>

//           <div className="features-center">
//             <Image
//               src="/circles.svg"
//               alt="Research features visualization"
//               width={350}
//               height={350}
//               priority={false}
//             />
//           </div>

//           <div className="features-col">
//             <div className="feature-card right-card dark-bar">
//               <h4>Live Message</h4>
//               <p>
//                 Share specific areas for improvement and set clear expectations.
//               </p>
//             </div>

//             <div className="feature-card right-card teal-bar">
//               <h4>24h/7 Service</h4>
//               <p>
//                 Address and promptly fix any service-related problems or delays.
//               </p>
//             </div>
//           </div>
//         </div>
//       </section>
//       <section className="explore">
//         <h2>
//           Explore <span>Research</span>
//         </h2>
//         <div className="explore-grid">
//           <div className="explore-card teal">
//             <span className="badge">
//               <Image
//                 src="/images/icons/cal.svg"
//                 alt="Research features visualization"
//                 width={25}
//                 height={25}
//                 priority={false}
//               />
//             </span>
//             <h4>Engineering</h4>
//             <img
//               src="/images/icons/tools.svg"
//               className="card-img"
//               alt="Engineering"
//             />
//           </div>
//           <div className="explore-card teal">
//             <span className="badge">
//               <Image
//                 src="/images/icons/mth.svg"
//                 alt="Research features visualization"
//                 width={25}
//                 height={25}
//                 priority={false}
//               />
//             </span>
//             <h4>Math</h4>
//             <img
//               src="/images/icons/maths.svg"
//               className="card-img"
//               alt="maths"
//             />
//           </div>
//           <div className="explore-card dark">
//             <span className="badge">
//               <Image
//                 src="/images/icons/mth.svg"
//                 alt="Research features visualization"
//                 width={25}
//                 height={25}
//                 priority={false}
//               />
//             </span>
//             <h4>Medicine</h4>
//             <img
//               src="/images/icons/mdsn.svg"
//               className="card-img-ops"
//               alt="Medicine"
//             />
//           </div>
//           <div className="explore-card dark">
//             <span className="badge">
//               <Image
//                 src="/images/icons/mth.svg"
//                 alt="Research features visualization"
//                 width={25}
//                 height={25}
//                 priority={false}
//               />
//             </span>
//             <h4>Social</h4>
//             <img
//               src="/images/icons/ssl.svg"
//               className="card-img-ops"
//               alt="Social"
//             />
//           </div>
//           <div className="explore-card teal">
//             <span className="badge">
//               <Image
//                 src="/images/icons/cal.svg"
//                 alt="Research features visualization"
//                 width={25}
//                 height={25}
//                 priority={false}
//               />
//             </span>
//             <h4>Climate</h4>
//             <img
//               src="/images/icons/clmt.svg"
//               className="card-img"
//               alt="Climate"
//             />
//           </div>
//           <div className="explore-card teal">
//             <span className="badge">
//               <Image
//                 src="/images/icons/cal.svg"
//                 alt="Research features visualization"
//                 width={25}
//                 height={25}
//                 priority={false}
//               />
//             </span>
//             <h4>Science</h4>
//             <img
//               src="/images/icons/sci.svg"
//               className="card-img"
//               alt="Science"
//             />
//           </div>
//           <div className="explore-card teal">
//             <span className="badge">
//               <Image
//                 src="/images/icons/cal.svg"
//                 alt="Research features visualization"
//                 width={25}
//                 height={25}
//                 priority={false}
//               />
//             </span>
//             <h4>Business</h4>
//             <img
//               src="/images/icons/buz.svg"
//               className="card-img"
//               alt="Business"
//             />
//           </div>
//           <div className="explore-card dark">
//             <span className="badge">
//               <Image
//                 src="/images/icons/mth.svg"
//                 alt="Research features visualization"
//                 width={25}
//                 height={25}
//                 priority={false}
//               />
//             </span>
//             <h4>Article</h4>
//             <img
//               src="/images/icons/artcl.svg"
//               className="card-img-ops"
//               alt="Article"
//             />
//           </div>
//         </div>
//       </section>
//       <section className="news">
//         <h2>
//           {" "}
//           Latest <span>News</span>{" "}
//         </h2>
//         <p className="news-sub">
//           {" "}
//           The Summit offers a range of sessions that provide educators the
//           opportunity to interact and learn from each other.{" "}
//         </p>
//         <div className="news-grid">
//           <div className="news-card">
//             <Image
//               src="/images/event.jpg"
//               alt="Event news"
//               fill
//               className="news-image"
//             />

//             <div className="news-overlay">
//               <p>
//                 NEW RESEARCH REVEALS <br />
//                 BREAKTHROUGH IN AI-DRIVEN <br />
//                 HEALTHCARE DIAGNOSTICS
//               </p>
//               <span className="arrow">→</span>
//             </div>
//           </div>
//           <div className="news-card">
//             <Image
//               src="/images/envt.jpg"
//               alt="Event news"
//               fill
//               className="news-image"
//             />

//             <div className="news-overlay">
//               <p>
//                 NEW RESEARCH REVEALS <br />
//                 BREAKTHROUGH IN AI-DRIVEN <br />
//                 HEALTHCARE DIAGNOSTICS
//               </p>
//               <span className="arrow">→</span>
//             </div>
//           </div>
//           <div className="news-card">
//             <Image
//               src="/images/evt.jpg"
//               alt="Event news"
//               fill
//               className="news-image"
//             />

//             <div className="news-overlay">
//               <p>
//                 NEW RESEARCH REVEALS <br />
//                 BREAKTHROUGH IN AI-DRIVEN <br />
//                 HEALTHCARE DIAGNOSTICS
//               </p>
//               <span className="arrow">→</span>
//             </div>
//           </div>
//           <div className="news-card">
//             <Image
//               src="/images/etv.jpg"
//               alt="Event news"
//               fill
//               className="news-image"
//             />

//             <div className="news-overlay">
//               <p>
//                 NEW RESEARCH REVEALS <br />
//                 BREAKTHROUGH IN AI-DRIVEN <br />
//                 HEALTHCARE DIAGNOSTICS
//               </p>
//               <span className="arrow">→</span>
//             </div>
//           </div>
//         </div>
//         <div className="dots">
//           {" "}
//           <span></span>
//           <span></span>
//           <span></span>
//           <span></span>
//           <span></span>{" "}
//         </div>
//       </section>
//       <section className="i-event-section">
//         <h2>
//           {" "}
//           Upcoming <span>Events</span>{" "}
//         </h2>
//         <div className="i-event">
//           <div className="i-event-overlay">
//             <div className="i-event-left">
//               <h3>Innovate & Research Summit</h3>

//               <p className="date">30th November • St. Louis</p>

//               <button className="register-btn">Register Now</button>
//             </div>

//             <div className="i-event-right">
//               <p>
//                 BSU Academic Summit is an annual conference where educators
//                 under the BSU umbrella can share their knowledge, learn, and
//                 empower each other.
//               </p>
//             </div>
//           </div>
//         </div>
//       </section>
//       <section className="sponsor-section"></section>
//       <section className="sponsor">
//         <div className="sponsor-wrapper">
//           <div className="sponsor-card">
//             <h3 className="sponsor-title">
//               Sponsorships
//               <span className="line"></span>
//             </h3>
//             <div className="sponsor-logos">
//               <span className="logo">
//                 <Image
//                   src="/images/universapulsar.png"
//                   alt="UniversaPulsar"
//                   width={160}
//                   height={40}
//                 />
//               </span>
//               <span className="logo">
//                 <Image
//                   src="/images/evora.png"
//                   alt="Evora"
//                   width={110}
//                   height={40}
//                 />
//               </span>
//               <span className="logo">
//                 <Image
//                   src="/images/universapulsar.png"
//                   alt="UniversaPulsar"
//                   width={160}
//                   height={40}
//                 />
//               </span>
//               <span className="logo">
//                 <Image
//                   src="/images/evora.png"
//                   alt="Evora"
//                   width={110}
//                   height={40}
//                 />
//               </span>
//               <span className="logo">
//                 <Image
//                   src="/images/universapulsar.png"
//                   alt="UniversaPulsar"
//                   width={160}
//                   height={40}
//                 />
//               </span>
//             </div>
//           </div>
//           <div className="sponsor-shadow"></div>
//         </div>
//       </section>
//       <footer className="site-footer">
//         <div className="footer-top">
//           <div className="footer-left">
//             <div className="logo">
//               <Image
//                 src="/logo.svg"
//                 alt="ResearchCrest Logo"
//                 width={160}
//                 height={40}
//                 priority
//               />
//             </div>
//             <p>Stay in the know by subscribing to our newsletter below</p>
//             <div className="newsletter">
//               <input type="email" placeholder="Enter your email address" />
//               <button>→</button>
//             </div>
//           </div>

//           <div className="footer-right">
//             <div className="footer-col">
//               <h4>Contact</h4>
//               <a href="#">Contact Form</a>
//               <a href="#">FAQ</a>
//               <a href="#">Privacy Policy</a>
//               <a href="#">T&amp;C</a>
//             </div>

//             <div className="footer-col">
//               <h4>Social</h4>
//               <a href="#">Facebook</a>
//               <a href="#">Youtube</a>
//               <a href="#">Twitter</a>
//               <a href="#">LinkedIn</a>
//             </div>
//           </div>
//         </div>

//         <div className="footer-bottom">
//           <span>© ResearhCrest. All Rights Reserved 2026</span>
//           <a href="#">Terms &amp; Conditions</a>
//         </div>
//       </footer>
//     </>
//   );
// }
