import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>ResearchCrest – Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="navbar">
        <div className="logo">
          Research<span>Crest</span>
        </div>
        <nav>
          <a href="#">App</a>
          <a href="#">Join</a>
          <a href="#">Sign in</a>
          <a href="#">Help Center</a>
        </nav>
      </header>

      <section className="hero">
        <div className="hero-left">
          <h1>
            “Research with Purpose.
            <br />
            Impact with Vision.”
          </h1>
          <p>
            Ready-to-use placeholder text for a researcher website’s hero
            section. Short, medium, long plus classic lorem ipsum paragraph.
          </p>

          <div className="stats">
            <div>
              Profiles <strong>2M+</strong>
            </div>
            <div>
              Visitors <strong>10M+</strong>
            </div>
            <div>
              Industry Expert <strong>2M+</strong>
            </div>
            <div>
              Audience <strong>2M+</strong>
            </div>
          </div>

          <div className="hero-buttons">
            <button className="btn primary">Register Now</button>
            <button className="btn secondary">Learn More</button>
          </div>
        </div>

        <div className="hero-right">
          <div className="login-card">
            <h2>Welcome to ResearchCrest</h2>

            <label>Name</label>
            <input type="text" value="Login" />

            <label>Email or Phone</label>
            <input type="email" value="bevan@gmail.com" />

            <label>Password</label>
            <input type="password" value="**********" />

            <button className="login-btn">🔒 Log in</button>

            <div className="login-links">
              <a href="#">Forgot password</a>
              <a href="#">Create new account</a>
            </div>
          </div>
        </div>
      </section>

      <section className="research-features">
        <h2>
          Research <span>Features</span>
        </h2>

        <div className="features-layout">
          <div className="features-col">
            <div className="feature-card teal-bar">
              <h4>Performance graph and cart</h4>
              <p>
                Track delivery, quality, and reliability metrics on a consistent
                basis.
              </p>
            </div>

            <div className="feature-card dark-bar">
              <h4>AI chatbot and timeline</h4>
              <p>
                Continue or formally end the partnership based on overall
                performance.
              </p>
            </div>
          </div>

          <div className="features-center">
            <div className="circle teal">
              <span className="step">01</span>
              <span className="icon">
                <img
                  className="icon-img"
                  src="./public/icons/chart.svg"
                  alt="chart icon"
                />
              </span>
            </div>

            <div className="circle dark">
              <span className="step">02</span>
              <span className="icon">💬</span>
            </div>

            <div className="circle dark">
              <span className="step">03</span>
              <span className="icon">〰</span>
            </div>

            <div className="circle teal">
              <span className="step">04</span>
              <span className="icon">24h</span>
            </div>
          </div>

          <div className="features-col">
            <div className="feature-card dark-bar">
              <h4>Live Message</h4>
              <p>
                Share specific areas for improvement and set clear expectations.
              </p>
            </div>

            <div className="feature-card teal-bar">
              <h4>24h/7 Service</h4>
              <p>
                Address and promptly fix any service-related problems or delays.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="explore">
        <h2>
          Explore <span>Research</span>
        </h2>

        <div className="explore-grid">
          <div className="explore-card teal">Engineering</div>
          <div className="explore-card teal">Math</div>
          <div className="explore-card dark">Medicine</div>
          <div className="explore-card dark">Social</div>
          <div className="explore-card teal">Climate</div>
          <div className="explore-card teal">Science</div>
          <div className="explore-card teal">Business</div>
          <div className="explore-card dark">Article</div>
        </div>
      </section>

      <section className="news">
        <h2>
          latest <span>News</span>
        </h2>
        <p className="news-sub">
          The Summit offers a range of sessions that provide educators the
          opportunity to interact and learn from each other.
        </p>

        <div className="news-grid">
          <div className="news-card">
            <img src="https://via.placeholder.com/350x220" alt="" />
            <div className="news-tag">
              NEW RESEARCH REVEALS <br />
              BREAKTHROUGH IN AI-DRIVEN <br />
              HEALTHCARE DIAGNOSTICS
            </div>
          </div>

          <div className="news-card">
            <img src="https://via.placeholder.com/350x220" alt="" />
            <div className="news-tag">
              NEW RESEARCH REVEALS <br />
              BREAKTHROUGH IN AI-DRIVEN <br />
              HEALTHCARE DIAGNOSTICS
            </div>
          </div>

          <div className="news-card">
            <img src="https://via.placeholder.com/350x220" alt="" />
            <div className="news-tag">
              NEW RESEARCH REVEALS <br />
              BREAKTHROUGH IN AI-DRIVEN <br />
              HEALTHCARE DIAGNOSTICS
            </div>
          </div>
        </div>

        <div className="dots">
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </section>

      <section className="event">
        <div className="event-overlay">
          <div className="event-left">
            <h3>
              Upcoming
              <br />
              Event
            </h3>
            <p className="date">30th November • St. Louis</p>
            <button>Register Now</button>
          </div>

          <div className="event-right">
            <p>
              BSU Academic Summit is an annual conference where educators under
              the BSU umbrella can share their knowledge, learn, and empower
              each other.
            </p>
          </div>
        </div>
      </section>

      <section className="sponsor">
        <h3>Sponsorship</h3>
        <div className="sponsor-box">
          <span>GIGGLING</span>
          <span>UNIVERSITY</span>
          <span>ONEPLUS</span>
          <span>realme</span>
          <span>SANS</span>
        </div>
      </section>

      <footer className="footer">
        <div className="footer-grid">
          <div>
            <h4>ResearchCrest</h4>
            <p>Stay in the know by subscribing to our newsletter below.</p>
            <div className="newsletter">
              <input type="email" placeholder="Enter your email address" />
              <button>→</button>
            </div>
          </div>

          <div>
            <h4>Contact</h4>
            <a href="#">Contact Form</a>
            <a href="#">FAQ</a>
            <a href="#">Privacy Policy</a>
            <a href="#">T&C</a>
          </div>

          <div>
            <h4>Social</h4>
            <a href="#">Facebook</a>
            <a href="#">Youtube</a>
            <a href="#">Twitter</a>
            <a href="#">LinkedIn</a>
          </div>
          <div>
            <h4>Location</h4>
            <a href="#">LARGO DOS COLEGIAIS, 2 ÉVORA 7004-516, Portugal</a>
          </div>
        </div>

        <div className="footer-bottom">
          <span>© Researchcrest. All Rights Reserved 2023</span>
          <span>Terms & Conditions</span>
        </div>
      </footer>
    </>
  );
}
