import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function ProfilePage() {
  return (
    <>
      <Head>
        <title>ResearchCrest – Profile Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <!-- ================= NAVBAR ================= --> */}
      <header className="nav">
        <div className="logo">ResearchCrest</div>

        <div className="search">
          <input type="text" placeholder="Best Pizza Near Me" />
        </div>

        <nav className="menu">
          <a>Home</a>
          <a>Q&amp;A</a>
          <a>Network</a>
          <a>career</a>
          <a>Scholarship</a>
          <span className="icon"></span>
          <span className="icon"></span>
        </nav>
      </header>
      {/* <!-- ================= HERO ================= --> */}
      <section className="hero">
        <div className="hero-left">
          <span className="iam">I Am</span>
          <h1>Brand Gardner</h1>
          <p className="role">
            Assistant General Manager - HR | Business HR & Strategy
          </p>
          <p className="degree">MHRM (University of London)</p>
          <div className="followers">
            <span>300+ connections</span>
            <span>465 Followers</span>
          </div>
          <div className="meta">
            <span>📧 gardner@gmail.com</span>
            <span>📍 Location: St. London Street, Southern Park</span>
          </div>
          <div className="pills">
            <span>CSE</span>
            <span>Current Affiliations: 50</span>
          </div>
          <div className="social">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      </section>
      {/* <!-- 🔴 HERO END HERE (VERY IMPORTANT) --> */}
      {/* <!-- ================= PAGE BODY ================= --> */}
      <section className="page-body">
        {/* <!-- ================= MAIN ================= --> */}
        <main className="main">
          <div className="profile-tabs">
            <button className="tab active">Overview</button>
            <button className="tab">Research Area</button>
            <button className="tab">Publications</button>
            <button className="tab">Network</button>
            <button className="tab">Projects</button>
            <button className="tab">Awards</button>
            <button className="tab">Career</button>
          </div>
          <div className="content-card about-card">
            <h3>About</h3>
            <p>
              Works on trustworthy AI, with a focus on computer vision,
              fairness, and multimodal learning systems applied to real-world
              problems. Lorem Ipsum is simply dummy text of the printing and
              typesetting industry.
            </p>
          </div>
          <section className="education-card">
            <h3 className="edu-title">Education</h3>
            <div className="edu-grid">
              <div className="edu-left">
                <span className="edu-year">2012 – 2014</span>
                <strong className="edu-university">Fauget University</strong>
              </div>
              <div className="edu-right">
                <strong className="edu-degree">
                  Master of Science in Marketing
                </strong>
                <span className="edu-gpa">3.85 / 4 GPA</span>
              </div>
              <div className="edu-left">
                <span className="edu-year">2008 – 2011</span>
                <strong className="edu-university">Borcelle University</strong>
              </div>
              <div className="edu-right">
                <strong className="edu-degree">
                  Bachelor of Science in Marketing
                </strong>
                <span className="edu-gpa">3.7 / 4 GPA</span>
              </div>
            </div>
          </section>
          <section className="analytics-card">
            <h3 className="analytics-title">Analytics</h3>
            <div className="analytics-row">
              <div className="analytics-left">
                <div className="info-block">
                  <span>Total Views</span>
                  <strong>137</strong>
                </div>
                <div className="info-block">
                  <span>Search Apperence</span>
                  <strong>121 – 128</strong>
                </div>
              </div>
              <div className="analytics-right">
                <div className="donut-chart"></div>
                <div className="legend">
                  <span>
                    <i className="dot dark"></i> Total Views
                  </span>
                  <span>
                    <i className="dot light"></i> Search Apperence
                  </span>
                </div>
              </div>
            </div>
          </section>
          <section className="skills-card">
            <h3 className="skills-title">Skills</h3>
            <div className="skills-list">
              <span className="skill dark">Open AI</span>
              <span className="skill dark">Java</span>
              <span className="skill dark">C#</span>
              <span className="skill green">AWS EC2</span>
              <span className="skill dark">.net</span>
              <span className="skill green">R</span>
              <span className="skill green">Python</span>
            </div>
          </section>
          <section className="timeline-box">
            <div className="timeline-header">
              <h3>Timeline</h3>
              <span className="ai">✨ AI Overview</span>
            </div>
            <div className="timeline-wrapper">
              <div className="timeline-top">
                <div className="event">
                  <span className="dot"></span>
                  <p>Best Paper – CVPR</p>
                </div>
                <div className="event">
                  <span className="dot"></span>
                  <p>Completed M.Sc. in Computer Science</p>
                </div>
                <div className="event">
                  <span className="dot"></span>
                  <p>Internship at Google AI</p>
                </div>
              </div>
              <div className="timeline-bar">
                <div className="bar-seg dark"></div>
                <div className="bar-seg green"></div>
                <div className="bar-seg dark"></div>
                <div className="bar-arrow"></div>
              </div>
              <div className="timeline-bottom">
                <p>NSF Career Award</p>
                <p>Founded Fairness Lab</p>
                <p>Internship at Google AI</p>
              </div>
            </div>
          </section>
        </main>
        {/* <!-- ================= RIGHT COLUMN ================= --> */}
        <div className="hero-right">
          {/* <!-- RIGHT COLUMN --> */}
          {/* <!---------<div className="hero-right">
  <!-- PROFILE CARD --> */}
          <aside className="hero-card">
            <div className="card-top">
              <img
                className="card-avatar"
                src="https://randomuser.me/api/portraits/men/32.jpg"
              />
              <button className="download-btn">⬇</button>
            </div>
            <div className="card-actions">
              <button className="btn-connect">Connect</button>
              <button className="btn-message">Message</button>
            </div>
            <div className="stats">
              <div>
                <span>Publications</span>
                <b>42</b>
              </div>
              <div>
                <span>h-index</span>
                <b>18</b>
              </div>
              <div>
                <span>i10-index</span>
                <b>324</b>
              </div>
            </div>
            <div className="section">
              <h4>Domain & Classification</h4>
              <p>
                Electrical Engineering
                <br />
                Faculty of Technology
                <br />
                Advanced Polymers and Composite Research Group
              </p>
            </div>
            <div className="section">
              <h4>Research Interests</h4>
              <p>
                Renewable Energy
                <br />
                Internet of Things
                <br />
                Machine Learning
              </p>
            </div>
            <div className="section">
              <h4>Advisors</h4>
              <p className="green">
                Dr. Emily Carter
                <br />
                Dr. Steven Harris
                <br />
                Prof. Dr. Jonathan Miles
                <br />
                Dr. Rebecca Thornton
              </p>
            </div>
            <div className="section">
              <h4>Responsibilities</h4>
              <ul>
                <li>Introduction to Materials and Manufacturing</li>
                <li>Materials and Manufacturing</li>
                <li>Sustainable Development</li>
                <li>Environmental Management</li>
                <li>Design and Sustainable Development</li>
                <li>Learning Module, Module Coordinator</li>
              </ul>
            </div>
          </aside>
          <aside className="right-sidebar">
            {/* <!-- NOTABLE --> */}
            <div className="side-card">
              <div className="side-header">
                <h4>Notable</h4>
                <span className="dots">•••</span>
              </div>
              <div className="notable-row">
                <div className="notable-user">
                  <img src="https://randomuser.me/api/portraits/men/45.jpg" />
                  <p className="name">Alfredo</p>
                  <p className="role">Professor</p>
                  <div className="icons">◎ ◎</div>
                </div>
                <div className="notable-user">
                  <img src="https://randomuser.me/api/portraits/women/52.jpg" />
                  <p className="name">Cahaya</p>
                  <p className="role">Teacher</p>
                  <div className="icons">◎ ◎</div>
                </div>
                <div className="notable-user">
                  <img src="https://randomuser.me/api/portraits/women/68.jpg" />
                  <p className="name">Mariana</p>
                  <p className="role">Student</p>
                  <div className="icons">◎ ◎</div>
                </div>
              </div>
            </div>

            {/* <!-- YOU MIGHT LIKE --> */}
            <div className="side-card">
              <h4 className="simple-title">You might like</h4>
              <p className="sub">Pages for you</p>

              <div className="follow-item">
                <img src="https://randomuser.me/api/portraits/men/33.jpg" />
                <span>Science grup</span>
                <button>+ Follow</button>
              </div>

              <div className="follow-item">
                <img src="https://randomuser.me/api/portraits/men/61.jpg" />
                <span>Exois</span>
                <button>+ Follow</button>
              </div>
            </div>

            {/* <!-- NOTABLE RESEARCHER --> */}
            <div className="side-card">
              <div className="side-header">
                <h4>Notable Researcher</h4>
                <span className="dots">•••</span>
              </div>

              <div className="researcher">
                <img src="https://randomuser.me/api/portraits/women/44.jpg" />
                <div>
                  <p className="name">Liciera Band</p>
                  <span>Professor</span>
                </div>
              </div>

              <div className="researcher">
                <img src="https://randomuser.me/api/portraits/men/77.jpg" />
                <div>
                  <p className="name">Yad Amari</p>
                  <span>Lecturer</span>
                </div>
              </div>
            </div>
          </aside>
        </div>
      </section>
      {/* <!-- 🔴 PAGE BODY END -->
<!-- ================= FOOTER ================= --> */}
      <footer className="site-footer">
        <div className="footer-top">
          <div className="footer-left">
            <h3 className="footer-logo">ResearchCrest</h3>
            <p>Stay in the know by subscribing to our newsletter below</p>
            <div className="newsletter">
              <input type="email" placeholder="Enter your email address" />
              <button>→</button>
            </div>
          </div>

          <div className="footer-right">
            <div className="footer-col">
              <h4>Contact</h4>
              <a href="#">Contact Form</a>
              <a href="#">FAQ</a>
              <a href="#">Privacy Policy</a>
              <a href="#">T&amp;C</a>
            </div>

            <div className="footer-col">
              <h4>Social</h4>
              <a href="#">Facebook</a>
              <a href="#">Youtube</a>
              <a href="#">Twitter</a>
              <a href="#">LinkedIn</a>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <span>© Researchcrest. All Rights Reserved 2023</span>
          <a href="#">Terms &amp; Conditions</a>
        </div>
      </footer>
    </>
  );
}
