import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Carousel } from "react-bootstrap";
import { Geist, Geist_Mono } from "next/font/google";
import { FaLink, FaEnvelope } from "react-icons/fa";
import { HiOutlineDotsHorizontal } from "react-icons/hi";
import { FaUserPlus } from "react-icons/fa6";
import { IoIosArrowDown, IoMdNotificationsOutline } from "react-icons/io";
import { TbGridDots } from "react-icons/tb";
import { MdOutlineMail, MdOutlineLocationOn } from "react-icons/md";
import { FaFacebook } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Timeline ডেটা array
const timelineData = [
  { text: "NSF Career Award", year: 1970 },
  { text: "Best Paper - CVPR", year: 1980 },
  { text: "Best Researchers Award", year: 1990 },
  { text: "Best Youth Award", year: 2000 },
];

const researcherData = [
  {
    name: "Licorla Bond",
    role: "Lecturer",
    img: "https://randomuser.me/api/portraits/women/34.jpg",
    link: "/researcher/licorla",
  },
  {
    name: "Yousf Amari",
    role: "Professor",
    img: "https://randomuser.me/api/portraits/women/33.jpg",
    link: "/researcher/yousf",
  },
  {
    name: "Emma Watson",
    role: "Senior Scientist",
    img: "https://randomuser.me/api/portraits/women/65.jpg",
    link: "/researcher/emma",
  },
  {
    name: "John Miller",
    role: "Research Fellow",
    img: "https://randomuser.me/api/portraits/men/45.jpg",
    link: "/researcher/john",
  },
  {
    name: "Emma Watson",
    role: "Senior Scientist",
    img: "https://randomuser.me/api/portraits/women/65.jpg",
    link: "/researcher/emma",
  },
  {
    name: "John Miller",
    role: "Research Fellow",
    img: "https://randomuser.me/api/portraits/men/45.jpg",
    link: "/researcher/john",
  },
];

// ---------------- UTILITY (chunk array) ----------------
const chunkArray = (arr: any[], size: number) => {
  const chunks = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
};

const slides = chunkArray(researcherData, 2);

const pieData = [
  { title: "Quantum Computing", value: 19.7, color: "#041c4b" },
  { title: "Fingerprint", value: 15.2, color: "#13b7a6" },
  { title: "Data Science", value: 12.1, color: "#1f4ed8" },
  { title: "Cloud Computing", value: 22.7, color: "#0b6f6b" },
  { title: "HRM", value: 30.3, color: "#052e2b" },
];

const pData = [
  { title: "Quantum Computing", value: 19.7, color: "#041c4b" },
  { title: "Fingerprint", value: 15.2, color: "#13b7a6" },
  { title: "Data Science", value: 12.1, color: "#1f4ed8" },
  { title: "Cloud Computing", value: 22.7, color: "#0b6f6b" },
  { title: "HRM", value: 30.3, color: "#052e2b" },
];

const rdius = 80;
const cx = 100;
const cy = 100;

function polarToCartesian(cx, cy, r, angle) {
  const rad = ((angle - 90) * Math.PI) / 180.0;
  return {
    x: cx + r * Math.cos(rad),
    y: cy + r * Math.sin(rad),
  };
}

function describeArc(cx, cy, r, startAngle, endAngle) {
  const start = polarToCartesian(cx, cy, r, endAngle);
  const end = polarToCartesian(cx, cy, r, startAngle);
  const largeArcFlag = endAngle - startAngle <= 180 ? "0" : "1";

  return `
    M ${cx} ${cy}
    L ${start.x} ${start.y}
    A ${r} ${r} 0 ${largeArcFlag} 0 ${end.x} ${end.y}
    Z
  `;
}

export default function ResearchPage() {
  const router = useRouter();
  let current = 0;

  const gradient = pieData
    .map((item) => {
      const start = current;
      current += item.value;
      return `${item.color} ${start}% ${current}%`;
    })
    .join(", ");
  let angle = 0;
useEffect(() => {
  const tooltip = document.getElementById("pieTooltip");

  document.querySelectorAll(".pie-slice").forEach((slice) => {
    slice.addEventListener("mousemove", (e) => {
      tooltip.style.opacity = "1";
      tooltip.style.left = e.offsetX + 15 + "px";
      tooltip.style.top = e.offsetY + "px";
      tooltip.innerHTML = `
        <b>${slice.dataset.title}</b><br/>
        ${slice.dataset.value}
      `;
    });

    slice.addEventListener("mouseleave", () => {
      tooltip.style.opacity = "0";
    });
  });
}, []);

  return (
    <>
      <Head>
        <title>ResearchCrest – Profile Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
      </Head>
      <header className="fnav">
        <div className="logo">
          <Image
            src="/logo.svg"
            alt="ResearchCrest Logo"
            width={160}
            height={40}
            priority
          />
        </div>
        <div className="search">
          <input type="text" placeholder="Search In Research Crest" />
        </div>
        <nav className="feed-menu">
          <a>Home</a>
          <a>Q&amp;A</a>
          <a>Network</a>
          <a>Career</a>
          <a>Scholarship</a>
          <a href="#" className="nine-dots">
            <TbGridDots
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.2rem",
                color: "#000",
              }}
            />
          </a>
          <a>
            <IoMdNotificationsOutline
              style={{
                verticalAlign: "middle",
                marginLeft: "6px",
                fontSize: "1.3rem",
                color: "#000",
              }}
            />
          </a>
          <a className="profile-wrapper">
            <img src="/images/prof.jpg" alt="" className="menu-logo" />
            <IoIosArrowDown className="arrow-icon" />
          </a>
        </nav>
      </header>
      <section className="profile-page">
        <section className="profile-wrap">
          <section className="pdng-hero"></section>
          <section className="prof-hero">
            <div className="prof-hero-bg">
              <img src="/images/cvr.jpg" alt="Profile Background" />
              <div className="hero-overlay">
                <div className="prof-hero-left">
                  <p className="introo">I am</p>
                  <h1 className="name">Brand Gardner</h1>
                  <p className="desgnation">
                    Assistant General Manager – HR | Business HR & Strategy
                    <br />
                    MHRM (University of London)
                  </p>
                  <div className="sttcs">
                    <span>300+ connections</span>
                    <span>465 Followers</span>
                  </div>
                  <div className="cntact-info">
                    <p>
                      <MdOutlineMail /> gardner@gmail.com
                    </p>
                    <p>
                      <MdOutlineLocationOn /> Location: St. London Street,
                      Southern Park
                    </p>
                  </div>
                  <div className="tags">
                    <span className="tgg wht">CSE</span>
                    <span className="tgg wht">Current Affiliations: 50</span>
                    <span className="tgg icn">
                      <FaFacebook className="tag-icn" />
                    </span>
                    <span className="tgg icn">
                      <FaLinkedin className="tag-icn" />
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* <!-- MAIN GRID --> */}
          <section className="pfile-layut">
            {/* LEFT COLUMN */}
            <div className="pfl-main">
              <div className="profile-tabs-wrap">
                <div className="pfl-tabs">
                  <a className="tab">Overview</a>
                  <a className="tab active">Research Area</a>
                  <a className="tab">Publications</a>
                  <a className="tab">Network</a>
                  <a className="tab">Projects</a>
                  <a className="tab">Awards</a>
                  <a className="tab">Career</a>
                </div>
              </div>
              {/* Research Area Section */}
              <section className="research-section">
                  <div className="pie-svg-wrap">
      <svg width="200" height="200" className="pie-svg">
        {pData.map((item, i) => {
          const startAngle = angle;
          const endAngle = angle + (item.value / 100) * 360;
          angle = endAngle;

          return (
            <path
              key={i}
              d={describeArc(cx, cy, rdius, startAngle, endAngle)}
              fill={item.color}
              data-title={item.title}
              data-value={`${item.value}%`}
              className="pie-slice"
            />
          );
        })}
      </svg>

      <div className="pie-tooltip" id="pieTooltip"></div>
    </div>
              </section>
               <section className="research-section">
      <div className="research-card">
        <h4 className="card-title">Research Area</h4>
<div className="pie-area">
      <div
        className="pie"
        style={{ background: `conic-gradient(${gradient})` }}
      >
        {/* Tooltip */}
        <div className="pie-tooltip">
          {pieData.map((item, i) => (
            <div key={i}>
              {item.title} – {item.value}%
            </div>
          ))}
        </div>
      </div>

      {/* Labels around pie */}
      {pieData.map((item, index) => (
        <div
          key={index}
          className={`pie-float label-${index}`}
          style={{ color: item.color }}
        >
          {item.title}
          <b>{item.value}%</b>
        </div>
      ))}
    </div>
      </div>
    </section>
              <section className="research-section">
                <div className="research-card">
                  <h4 className="card-title">Research Area</h4>

                  <div className="pie-wrap">
                    <div className="pie"></div>
                  </div>

                  <div className="pie-labels">
                    <span>
                      Quantum Computing
                      <br />
                      <b>19.7%</b>
                    </span>
                    <span>
                      Fingerprint
                      <br />
                      <b>15.2%</b>
                    </span>
                    <span>
                      Data Science
                      <br />
                      <b>12.1%</b>
                    </span>
                    <span>
                      Cloud Computing
                      <br />
                      <b>22.7%</b>
                    </span>
                    <span>
                      HRM
                      <br />
                      <b>30.3%</b>
                    </span>
                  </div>

                  <h5 className="sub-title">Research Area chart</h5>
                  <p className="desc">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Quisque vulputate vel tortor ut lacus.
                  </p>
                </div>

                <div className="research-card">
                  <span className="small-title">Research Chart</span>
                  <h2 className="big-title">Data Infographic</h2>

                  <p className="info-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Quisque vulputate vel tortor ut lacus. Praesent imperdiet
                    magna sit amet gravida gravida.
                  </p>

                  <div className="bars">
                    <div className="bar-row">
                      <span className="label">Quantum Computing</span>
                      <div className="track">
                        {/* <i style="width:38%"></i> */}
                      </div>
                    </div>

                    <div className="bar-row">
                      <span className="label">HRM</span>
                      <div className="track">
                        {/* <i style="width:42%"></i> */}
                      </div>
                    </div>

                    <div className="bar-row">
                      <span className="label">Data Science</span>
                      <div className="track">
                        {/* <i style="width:30%"></i> */}
                      </div>
                    </div>

                    <div className="bar-row">
                      <span className="label">Item 4</span>
                      <div className="track">
                        {/* <i style="width:50%"></i> */}
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="eduction-card">
                <h4>Education</h4>

                <div className="eduu-row">
                  <div className="eduu-left">
                    <p className="eduu-university">Fauget University</p>
                    <span className="edu-year">2012 – 2014</span>
                  </div>
                  <div className="eduu-right">
                    <p className="edu-degree">Master of Science in Marketing</p>
                    <span className="edu-gpa">3.85 / 4 GPA</span>
                  </div>
                </div>
                <div className="eduu-row">
                  <div className="eduu-left">
                    <p className="edu-university">Borcelle University</p>
                    <span className="edu-year">2008 – 2011</span>
                  </div>
                  <div className="eduu-right">
                    <p className="edu-degree">
                      Bachelor of Science in Marketing
                    </p>
                    <span className="edu-gpa">3.7 / 4 GPA</span>
                  </div>
                </div>
              </section>
              <section className="anlytics-card">
                <h4 className="anlytics-title">Analytics</h4>

                <div className="analytics-content">
                  <div className="analytics-left">
                    <p className="metric-label">Total Views</p>
                    <span className="metric-range">35+</span>

                    <p className="metric-sub">Search Apperence</p>
                    <span className="metric-range">120</span>
                  </div>

                  <div className="analytics-right">
                    <div className="donut-chart"></div>
                    <div className="donut-legend">
                      <div>
                        <span className="dot dark"></span> Total Views
                      </div>
                      <div>
                        <span className="dot light"></span> Search Apperence
                      </div>
                      <div className="donut-link">Last 7 Days</div>
                    </div>
                  </div>
                </div>
              </section>
              <div className="sklls-card">
                <section className="skills-ref">
                  <h4>Skills</h4>

                  <div className="skills-ref-list">
                    <span className="skill-pill dark">Open AI</span>
                    <span className="skill-pill green">Java</span>
                    <span className="skill-pill dark">C#</span>
                    <span className="skill-pill green">AWS - EC2</span>
                    <span className="skill-pill dark">.net</span>
                    <span className="skill-pill green">R</span>
                    <span className="skill-pill dark">Python</span>
                    <span className="skill-pill green">Arduino</span>
                    <span className="skill-pill dark">C++</span>
                    <span className="skill-pill green">R</span>
                    <span className="skill-pill dark">MongoDB</span>
                  </div>
                </section>
              </div>
              <section className="tmln-card">
                {/* Header */}
                <div className="header-row">
                  <h4>Timeline</h4>
                  <div className="tmln-img">
                    <Image
                      src="/images/icons/aiimg.svg"
                      alt="ai image"
                      width={30}
                      height={30}
                    />
                  </div>
                </div>

                {/* Timeline */}
                <div className="sch-style-2">
                  <div className="sch-timeline-content">
                    {timelineData.map((item, index) => (
                      <div className="sch-content" key={index}>
                        {/* Text + Year */}
                        <div className="sch-data">
                          <div className="sch-text">{item.text}</div>
                          <div className="sch-year">{item.year}</div>
                        </div>

                        {/* Button */}
                        <button className="btn-right"></button>

                        {/* Odd → sch-down, Even → sch-up */}
                        {index % 2 === 0 ? (
                          <div className="sch-down">
                            <div className="sch-icon">
                              <i>{index + 1}</i>
                            </div>
                          </div>
                        ) : (
                          <div className="sch-up">
                            <div className="sch-icon">
                              <i>{index + 1}</i>
                            </div>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </section>
            </div>
            {/* <!-- RIGHT COLUMN --> */}
            <div className="pfl-right">
              <aside className="pfl-card">
                <div className="atr-wrap">
                  <img src="/images/prof.jpg" />
                  {/* <span className="badge">8+</span> */}
                </div>
                <div className="card-bttns">
                  <button className="btn-dark">
                    <FaLink /> Connect
                  </button>
                  <button className="btn-dark">
                    <FaEnvelope /> Message
                  </button>
                </div>

                <div className="card-stt">
                  <div className="stat">
                    <h4>42</h4>
                    <p>Publications</p>
                  </div>
                  <div className="stat">
                    <h4>18</h4>
                    <p>h-index</p>
                  </div>
                  <div className="stat">
                    <h4>324</h4>
                    <p>i10-index</p>
                  </div>
                </div>

                <div className="card-grid">
                  <div className="grid-label">Domain & Classification:</div>
                  <div className="grid-value">
                    Electrical Engineering
                    <br />
                    Faculty of Technology
                    <br />
                    Advanced Polymers
                  </div>

                  <div className="grid-label">Research Interests:</div>
                  <div className="grid-value">
                    Renewable Energy
                    <br />
                    Internet of Things
                    <br />
                    Machine Learning
                  </div>

                  <div className="grid-label">Advisors:</div>
                  <div className="grid-value"></div>
                  <div className="grid-label">PhD Advisors:</div>
                  <div className="grid-value">
                    <span className="green">Dr. Emily Carter</span>
                    <br />
                    <span className="green">Dr. Steven Harris</span>
                    <br />
                    <br />
                  </div>
                  <div className="grid-label">MS Advisors:</div>
                  <div className="grid-value">
                    <span className="green">Prof. Dr. Jonathan Miles</span>
                    <br />
                    <span className="green">Prof. Dr. Rebecca Thornton</span>
                    <br />
                    <br />
                  </div>
                  <div className="grid-label">Responsibilities:</div>
                  <div className="grid-value">
                    <ul className="resp-list">
                      <li>
                        Introduction to Materials and Manufacture (Module
                        Co-ordinator)
                      </li>
                      <li>Materials and Manufacture</li>
                      <li>
                        Sustainable Development and Environmental Management
                      </li>
                      <li>
                        Design and Sustainable Development (Distance Learning
                        Module)
                      </li>
                    </ul>
                  </div>
                </div>
              </aside>
              <section className="ntbl-researcher">
                {/* HEADER */}
                <div className="notable-head">
                  <h4>Notable Researcher</h4>
                </div>

                {/* CAROUSEL */}
                <Carousel
                  indicators={false}
                  controls
                  interval={null} // ✅ autoplay OFF
                >
                  {slides.map((group, index) => (
                    <Carousel.Item key={index}>
                      <div className="researcher-row">
                        {group.map((item, i) => (
                          <div className="rsrcher-item" key={i}>
                            <img src={item.img} alt={item.name} />

                            <div className="resrcher-info">
                              <h6>{item.name}</h6>
                              <p>{item.role}</p>
                              <a href={item.link}>See Details</a>
                            </div>
                          </div>
                        ))}
                      </div>
                    </Carousel.Item>
                  ))}
                </Carousel>
              </section>
              <div className="ntbles-card notable-card">
                <div className="side-header">
                  <h4>NOTABLE</h4>
                  <span>
                    <HiOutlineDotsHorizontal className="dots-icon" />
                  </span>
                </div>
                <Carousel
                  indicators={false}
                  controls={true}
                  interval={null}
                  className="notable-carousel"
                >
                  <Carousel.Item>
                    <div className="notable-row">
                      <div className="notable-user">
                        <img src="https://randomuser.me/api/portraits/men/45.jpg" />
                        <p>Alfredo</p>
                        <span>Professor</span>
                        <p className="sub">alfredo@gmail.com</p>
                      </div>
                      <div className="notable-user">
                        <img src="https://randomuser.me/api/portraits/women/52.jpg" />
                        <p>Cahaya</p>
                        <span>Teacher</span>
                        <p>cahaya@gmail.com</p>
                      </div>
                      <div className="notable-user">
                        <img src="https://randomuser.me/api/portraits/women/68.jpg" />
                        <p>Mariana</p>
                        <span>Student</span>
                        <p>mariana@gmail.com</p>
                      </div>
                    </div>
                  </Carousel.Item>
                  <Carousel.Item>
                    <div className="notable-row">
                      <div className="notable-user">
                        <img src="https://randomuser.me/api/portraits/men/46.jpg" />
                        <p>James</p>
                        <span>Professor</span>
                        <p className="sub">alfredo@gmail.com</p>
                      </div>
                      <div className="notable-user">
                        <img src="https://randomuser.me/api/portraits/women/53.jpg" />
                        <p>Susan</p>
                        <span>Teacher</span>
                        <p>susan@gmail.com</p>
                      </div>
                      <div className="notable-user">
                        <img src="https://randomuser.me/api/portraits/women/69.jpg" />
                        <p>Linda</p>
                        <span>Student</span>
                        <p>linda@gmail.com</p>
                      </div>
                    </div>
                  </Carousel.Item>
                </Carousel>
                <button className="read-more">SEE MORE</button>
              </div>
              <section className="suggst-section">
                <h4>You May Like</h4>
                <p className="subb">Pages for you</p>
                <div className="suggest-list">
                  <div className="suggest-item">
                    <div className="suggest-left">
                      <img
                        src="/images/scigrp.jpg"
                        className="suggest-avatar-img"
                      />
                      <span>Science Group</span>
                    </div>
                    <button className="follow-btn">
                      <FaUserPlus /> Follow
                    </button>
                  </div>
                  <div className="suggest-item">
                    <div className="suggest-left">
                      <img
                        src="https://randomuser.me/api/portraits/men/40.jpg"
                        className="suggest-avatar-img"
                      />
                      <span>Research Group</span>
                    </div>
                    <button className="follow-btn">
                      <FaUserPlus /> Follow
                    </button>
                  </div>
                </div>
              </section>
            </div>
          </section>
        </section>
      </section>
      {/* <!-- ================= FOOTER ================= --> */}
      <footer className="site-footer">
        <div className="footer-top">
          <div className="footer-left">
            <div className="logo">
              <Image
                src="/logo.svg"
                alt="ResearchCrest Logo"
                width={160}
                height={40}
                priority
              />
            </div>
            {/* <h3 className="footer-logo">ResearchCrest</h3> */}
            <p>Stay in the know by subscribing to our newsletter below</p>
            <div className="newsletter">
              <input type="email" placeholder="Enter your email address" />
              <button>→</button>
            </div>
          </div>

          <div className="footer-right">
            <div className="footer-col">
              <h4>Contact</h4>
              <a href="#">Contact Form</a>
              <a href="#">FAQ</a>
              <a href="#">Privacy Policy</a>
              <a href="#">T&amp;C</a>
            </div>

            <div className="footer-col">
              <h4>Social</h4>
              <a href="#">Facebook</a>
              <a href="#">Youtube</a>
              <a href="#">Twitter</a>
              <a href="#">LinkedIn</a>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <span>© Researchcrest. All Rights Reserved 2023</span>
          <a href="#">Terms &amp; Conditions</a>
        </div>
      </footer>
    </>
  );
}
