import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function ResearchPage() {
    const router = useRouter();
  return (
    <>
      <Head>
        <title>Research Crest – Research Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="nav">
        <div className="logo">ResearchCrest</div>

        <div className="search">
          <input type="text" placeholder="Best Pizza Near Me" />
        </div>

        <nav className="menu">
          <a>Home</a>
          <a>Q&amp;A</a>
          <a>Network</a>
          <a>career</a>
          <a>Scholarship</a>
          <span className="icon"></span>
          <span className="icon"></span>
        </nav>
      </header>
      <section className="profile-hero">
        <div className="profile-hero-left">
          <span className="iam">I Am</span>

          <h1>Brand Gardner</h1>
          <p className="role">
            Assistant General Manager - HR | Business HR & Strategy
          </p>
          <p className="degree">MHRM (University of London)</p>

          <div className="followers">
            <span>300+ connections</span>
            <span>465 Followers</span>
          </div>

          <div className="meta">
            <span>📧 gardner@gmail.com</span>
            <span>📍 Location: St. London Street, Southern Park</span>
          </div>

          <div className="pills">
            <span>CSE</span>
            <span>Current Affiliations: 50</span>
          </div>

          <div className="social">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      </section>
      <section className="page-body">
        <main className="main">
          <div className="profile-tabs">
            <button className="tab">Overview</button>
            <button className="tab active">Research Area</button>
            <button className="tab"
             onClick={() => router.push("/publications-page")}
             >Publications</button>
            <button className="tab">Network</button>
            <button className="tab">Projects</button>
            <button className="tab">Awards</button>
            <button className="tab">Career</button>
          </div>

          <section className="research-section">
            <div className="research-card">
              <h4 className="card-title">Researches</h4>

              <div className="pie-wrap">
                <div className="pie"></div>
              </div>

              <div className="pie-labels">
                <span>
                  Quantum Computing
                  <br />
                  <b>19.7%</b>
                </span>
                <span>
                  Fingerprint
                  <br />
                  <b>15.2%</b>
                </span>
                <span>
                  Data Science
                  <br />
                  <b>12.1%</b>
                </span>
                <span>
                  Cloud Computing
                  <br />
                  <b>22.7%</b>
                </span>
                <span>
                  HRM
                  <br />
                  <b>30.3%</b>
                </span>
              </div>

              <h5 className="sub-title">Research Area chart</h5>
              <p className="desc">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque
                vulputate vel tortor ut lacus.
              </p>
            </div>

            <div className="research-card">
              <span className="small-title">Research Chart</span>
              <h2 className="big-title">Data Infographic</h2>

              <p className="info-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque
                vulputate vel tortor ut lacus. Praesent imperdiet magna sit amet
                gravida gravida.
              </p>

              <div className="bars">
                <div className="bar-row">
                  <span className="label">Quantum Computing</span>
                  <div className="track">{/* <i style="width:38%"></i> */}</div>
                </div>

                <div className="bar-row">
                  <span className="label">HRM</span>
                  <div className="track">{/* <i style="width:42%"></i> */}</div>
                </div>

                <div className="bar-row">
                  <span className="label">Data Science</span>
                  <div className="track">{/* <i style="width:30%"></i> */}</div>
                </div>

                <div className="bar-row">
                  <span className="label">Item 4</span>
                  <div className="track">{/* <i style="width:50%"></i> */}</div>
                </div>
              </div>
            </div>
          </section>

          <section className="timeline-box">
            <div className="timeline-header">
              <h3>Timeline</h3>
              <span className="ai">✨ AI Overview</span>
            </div>

            <div className="timeline-wrapper">
              <div className="timeline-top">
                <div className="tevent">
                  <span className="dot"></span>
                  <p>Best Paper – CVPR</p>
                </div>
                <div className="tevent">
                  <span className="dot"></span>
                  <p>Completed M.Sc. in Computer Science</p>
                </div>
                <div className="tevent">
                  <span className="dot"></span>
                  <p>Internship at Google AI</p>
                </div>
              </div>
              <div className="timeline-bar">
                <div className="bar-seg dark"></div>
                <div className="bar-seg green"></div>
                <div className="bar-seg dark"></div>
                <div className="bar-arrow"></div>
              </div>
              <div className="timeline-bottom">
                <p>NSF Career Award</p>
                <p>Founded Fairness Lab</p>
                <p>Internship at Google AI</p>
              </div>
            </div>
          </section>
        </main>
        <div className="profile-hero-right">
          <aside className="profile-hero-card">
            <div className="card-top">
              <img
                className="card-avatar"
                src="https://randomuser.me/api/portraits/men/32.jpg"
              />
              <button className="download-btn">⬇</button>
            </div>

            <div className="card-actions">
              <button className="btn-connect">Connect</button>
              <button className="btn-message">Message</button>
            </div>

            <div className="stats">
              <div>
                <span>Publications</span>
                <b>42</b>
              </div>
              <div>
                <span>h-index</span>
                <b>18</b>
              </div>
              <div>
                <span>i10-index</span>
                <b>324</b>
              </div>
            </div>

            <div className="section">
              <h4>Domain & Classification</h4>
              <p>
                Electrical Engineering
                <br />
                Faculty of Technology
                <br />
                Advanced Polymers and Composite Research Group
              </p>
            </div>

            <div className="section">
              <h4>Research Interests</h4>
              <p>
                Renewable Energy
                <br />
                Internet of Things
                <br />
                Machine Learning
              </p>
            </div>

            <div className="section">
              <h4>Advisors</h4>
              <p className="green">
                Dr. Emily Carter
                <br />
                Dr. Steven Harris
                <br />
                Prof. Dr. Jonathan Miles
                <br />
                Dr. Rebecca Thornton
              </p>
            </div>

            <div className="section">
              <h4>Responsibilities</h4>
              <ul>
                <li>Introduction to Materials and Manufacturing</li>
                <li>Materials and Manufacturing</li>
                <li>Sustainable Development</li>
                <li>Environmental Management</li>
                <li>Design and Sustainable Development</li>
                <li>Learning Module, Module Coordinator</li>
              </ul>
            </div>
          </aside>

          <aside className="right-sidebar">
            <div className="side-card">
              <div className="side-header">
                <h4>Notable</h4>
                <span className="dots">•••</span>
              </div>

              <div className="notable-row">
                <div className="notable-user">
                  <img src="https://randomuser.me/api/portraits/men/45.jpg" />
                  <p className="name">Alfredo</p>
                  <p className="role">Professor</p>
                  <div className="icons">◎ ◎</div>
                </div>

                <div className="notable-user">
                  <img src="https://randomuser.me/api/portraits/women/52.jpg" />
                  <p className="name">Cahaya</p>
                  <p className="role">Teacher</p>
                  <div className="icons">◎ ◎</div>
                </div>

                <div className="notable-user">
                  <img src="https://randomuser.me/api/portraits/women/68.jpg" />
                  <p className="name">Mariana</p>
                  <p className="role">Student</p>
                  <div className="icons">◎ ◎</div>
                </div>
              </div>
            </div>
            <div className="side-card">
              <h4 className="simple-title">You might like</h4>
              <p className="sub">Pages for you</p>

              <div className="follow-item">
                <img src="https://randomuser.me/api/portraits/men/33.jpg" />
                <span>Science grup</span>
                <button>+ Follow</button>
              </div>

              <div className="follow-item">
                <img src="https://randomuser.me/api/portraits/men/61.jpg" />
                <span>Exois</span>
                <button>+ Follow</button>
              </div>
            </div>
            <div className="side-card">
              <div className="side-header">
                <h4>Notable Researcher</h4>
                <span className="dots">•••</span>
              </div>

              <div className="researcher">
                <img src="https://randomuser.me/api/portraits/women/44.jpg" />
                <div>
                  <p className="name">Liciera Band</p>
                  <span>Professor</span>
                </div>
              </div>

              <div className="researcher">
                <img src="https://randomuser.me/api/portraits/men/77.jpg" />
                <div>
                  <p className="name">Yad Amari</p>
                  <span>Lecturer</span>
                </div>
              </div>
            </div>
          </aside>
        </div>
      </section>
    </>
  );
}
